### ISSUE TITLE
Problem with file field 

### ISSUE THREAD

**Issue by Enrico68** [joostkremers/ebib#100]
Hello,

When I edit the `file` field and insert the file (say `barth2009.pdf`) I got the file field as `barth2009.pdf`. In order to use this bib file with other programs I need that the field file will be updated with the full path (e.g. `:/Users/enricopirani/Dropbox/PDF/barth2009.pdf:PDF`) Is there a way to get this solution. Thanks

**Comment by joostkremers** [comment]
Yes, Ebib always checks against the elements listed in `ebib-file-search-dirs` and chops off as much from the path of a pdf file as possible. If you don't want to use this functionality, the easiest way is to set that variable to `nil`. That should give you absolute file names.

**Comment by Enrico68** [comment]
Joost Kremers <notifications@github.com> writes:

> Yes, Ebib always checks against the elements listed in `ebib-file-search-dirs` and chops off as much from the path of a pdf file as possible. If you don't want to use this functionality, the easiest way is to set that variable to `nil`. That should give you absolute file names.
>
Thanks for your quick reply, turning off the variable I get the full path. But I
need the entry with the kind of file associated. Ebib is saving the file in this
way

file = {/Users/enricopirani/Dropbox/PDF/mongillo2006.pdf}

I need the file to be save in this way


file = {:/Users/enricopirani/Dropbox/PDF/mongillo2006.pdf:PDF}

I know is not a big problem but this would really help me a lot in order to have
the file open with other programs.

**Comment by joostkremers** [comment]
Well, you can always edit the file field directly by typing `C-u e` instead of just `e`. You won't have file name completion that way, but you can provide the format you need. Note, though, that with such a format, viewing files from within Ebib won't work.

**Comment by Enrico68** [comment]
Joost Kremers <notifications@github.com> writes:

> Well, you can always edit the file field directly by typing `C-u e` instead of just `e`. You won't have file name completion that way, but you can provide the format you need. Note, though, that with such a format, viewing files from within Ebib won't work.

Thanks again Joost, is there a way to have the full path of the file using the
ebib-file-search-dirs variable set to a specific folder instead of chopping off
the directory ? If not can we add this functionality ?

**Comment by joostkremers** [comment]
> Thanks again Joost, is there a way to have the full path of the file using the `ebib-file-search-dirs` variable set to a specific folder instead of chopping off the directory ? If not can we add this functionality ?

It's currently not possible but it shouldn't be too difficult to add.

With a little more work it should also be possible to add the colons and `PDF` tag to file names, and remove them again before opening a file.

Stay tuned, if I find some time I'll look into it.

**Comment by joostkremers** [comment]
I just added an option `ebib-truncate-file-names`: if unset, file names are always stored as absolute file names. See if it works and let me know if you run into trouble.

The second change will take some more time. I'll let you know when I get round to it.

**Comment by Enrico68** [comment]
I entered on [error](http://paste.openstack.org/show/561149/) whenever I try to modify the variable `ebib-truncate-file-names`

**Comment by joostkremers** [comment]
Apologies, should be fixed now.

**Comment by joostkremers** [comment]
The latest commit now adds an option to modify a file name before it's stored in the `file` field. Set `ebib-file-name-mod-function` to a function that takes two arguments, the first one the file name and the second one the direction of transformation, either `t` (to transform the name) or `nil` (to undo the transformations).

In your case, the following should work, at least for pdfs:

``` emacs-lisp
(defun my-modify-file-name (filename direction)
  "Modify FILENAME in DIRECTION."
  (if direction
      (concat ":" filename ":PDF")
    (substring filename 1 -4)))
```

This adds a colon to the front of the file name and `:PDF` to the end if `DIRECTION` is `t`, and removes it again if `DIRECTION` is `nil`. This is the simplest possible function, in all likelihood you'll want something a bit more sophisticated.

Let me know if it works for you.

**Comment by Enrico68** [comment]
I tried to customize the variable `ebib-file-name-mod-function` using the modfication function you proposed without success. I got error 
`````
custom-variable-mark-to-save: Saving ebib-file-name-mod-function: Invalid function: (defun my-modify-file-name (filename direction) "Modify FILENAME in DIRECTION." (if direction (concat ":" filename ":PDF") (substring filename 1 -4)))
`````

**Comment by joostkremers** [comment]
You seem to have set the function definition as the value of the option `ebib-file-name-mod-function`, but you should just set it to the name of the function, and the function should be defined in your init file.

Alternatively, you could set the option to an anonymous lambda function:

```emacs-lisp
(lambda (filename direction)
  (if direction
      (concat ":" filename ":PDF")
    (substring filename 1 -4)))
```

**Comment by Enrico68** [comment]
Joost Kremers <notifications@github.com> writes:

> You seem to have set the function definition as the value of the option `ebib-file-name-mod-function`, but you should just set it to the name of the function, and the function should be defined in your init file.
>
> Alternatively, you could set the option to an anonymous lambda function:
>
> ```emacs-lisp
> (lambda (filename direction)
>   (if direction
>       (concat ":" filename ":PDF")
>     (substring filename 1 -4)))
> ```

Thanks again Joost for your great support, this works perfectly!

**Comment by joostkremers** [comment]
Glad it works! Let me know if you run into any other issues.
