### ISSUE TITLE
Ebib does not call the external viewer correctly.

### ISSUE THREAD

**Issue by ReichKV** [joostkremers/ebib#103]
In my bib file i keep "file" entry in the form:
...
file = {~/Project/aaaa.pdf},
...

When i try to  call an external viewer (evince) i get:

Unable to open document “file:///home/rcv/~/Project/aaaa.pdf”.

So, i see that ebib automatically put "file:///home/rcv/" before it calls for the  viewer.

I look in the manual but didnot find how to prevent this.

**Comment by joostkremers** [comment]
Hmm, that might actually be a bug in Emacs. But there is an easy work-around that can be applied in Ebib and that is arguably better in any case, so I've pushed a fix. Should appear on Melpa in a few hours.

Thanks for reporting.

**Comment by ReichKV** [comment]
Thank you. in the last update i do not have this problem
