### ISSUE TITLE
Files in ebib-file-search-dirs not found

### ISSUE THREAD

**Issue by mhlinder** [joostkremers/ebib#105]
I've just upgraded to the most recent version, and now ebib can't find files named with the key name, located in directory `ebib-file-search-dirs`. Has the syntax for this changed?

I have in my .emacs file

```
 (setq ebib-file-search-dirs '("~/Dropbox/School/references/pdfs/"))
```

**Comment by joostkremers** [comment]
Thanks for reporting this!I rewrote the file finding code and somehow forgot about this option... It should be fixed in the latest commit.

If you still run into problems, do let me know!

**Comment by mhlinder** [comment]
Thanks! It works like a dream.

And thanks for making such useful software...

**Comment by joostkremers** [comment]
Great! Thanks for letting me know.

And I'm glad you find Ebib useful. :-)
