### ISSUE TITLE
"seq" as a  requiring package.

### ISSUE THREAD

**Issue by ReichKV** [joostkremers/ebib#106]
Hey,
After the last upgrade i were not able to start ebib without installing "seq"  package first.
 I think that one should add a "seq" package in the list of  requiring packages.

**Comment by joostkremers** [comment]
Hi,

The `seq` package is part of Emacs 25.1, but I didn't think of the fact that it wasn't included in Emacs 24, which I assume you're using.

I'll add the dependency and push it to Github as soon as possible. Thanks for reporting this!
