### ISSUE TITLE
'z' command does not properly minimze ebib

### ISSUE THREAD

**Issue by Brillow** [joostkremers/ebib#108]
With the newest version available on MELPA, the 'z' (I don't recall the actual name of the command) does no longer properly put ebib into the background. The entry-buffer, i.e. the one used for actually editing the entries, stays open.

**Comment by joostkremers** [comment]
Do you use multiple Emacs frames? If so, do you see any particular pattern when this problem crops up? I don't see the problem when I just start Ebib and press `z`.

**Comment by Brillow** [comment]
Just a single frame, but I am using emacsclient to connect to a daemon. Didn't have any problems with previous versions. I just tried it just using `emacs`, without the daemon, same problem.

I think I can reproduce it: Open ebib, 'o' to open a file, 'e' to edit an entry, 'q' to get back to the list. After this, if you press z, the entry buffer stays open.

**Comment by joostkremers** [comment]
Yes, I see it too, now. I'm not sure why it's happening... I'll take a closer look tomorrow and post here when I find a fix.

**Comment by joostkremers** [comment]
Should be fixed now. Let me know if you run into any problems.

Thanks for reporting this!
