### ISSUE TITLE
ebib-db-list-keys: Symbol's function definition is void: hash-table-keys

### ISSUE THREAD

**Issue by ReichKV** [joostkremers/ebib#109]
Hey,

After the last upgrade, i cannot start ebib.  I get following message "ebib-db-list-keys: Symbol's function definition is void: hash-table-keys". Could you help me with this?

The emacs version is 24.5

**Comment by joostkremers** [comment]
`hash-table-keys` is a function that was added in Emacs 24.4, so you should have it. Does it help if you do `(require 'subr-x)`?

**Comment by ReichKV** [comment]
I did this (require 'subr-x) and got new error Symbol's function definition is void: string-collate-lessp

**Comment by joostkremers** [comment]
I added a require statement for `subr-x` to make sure it's loaded when Ebib is started.

The function `string-collate-lessp` is new in Emacs 25. I added a check to make sure it exists and if not fall back on `string-lessp`, which does exist in Emacs 24. So it should work again now.

Sorry for the inconvenience and thanks for reporting.
