### ISSUE TITLE
Track org-ebib.el in only one repository

### ISSUE THREAD

**Issue by tarsius** [joostkremers/ebib#112]
`org-ebib.el` is tracked in the `ebib` repository as well as in the `org` repository. It would be better if there were just one canonical source - that way you don't have to commit every change twice (or risk that users don't get the latest fixes/features) due to the order of their `load-path`).

I have discussed other packages that have the same issue with Bastien (@bzg) before and in general he agrees that those packages should be removed from the org repository (see https://github.com/larstvei/ox-gfm/issues/14#issuecomment-257102966).

**Comment by bzg** [comment]
Yes, I confirm `org-ebib.el` shall not live in two separate places.  We also need to improve Worg documentation to update the list of available org-related packages.  Let me know when I can remove `org-ebib.el` from Org's `contrib/` directory.

**Comment by joostkremers** [comment]
Yes, I added `org-ebib.el` to the Ebib repo so it could be taken out of Org's `contrib/` directory. I just forgot to notify the Org mailing list. As far as I'm concerned, `org-ebib.el` can be removed `contrib/` now.

**Comment by bzg** [comment]
Done in Org master branch, thanks!

**Comment by tarsius** [comment]
Thanks you two!
