### ISSUE TITLE
Pull year from date field

### ISSUE THREAD

**Issue by patrl** [joostkremers/ebib#120]
When the `ebib-bibtex-dialect` is set to `biblatex`, `ebib` (and also `ebib-ivy-insert-citation`) should display the year from the `date` field, rather than the `year` field, since the value from `date` overrides `year` by default in `biblatex`.

**Comment by joostkremers** [comment]
True. Thanks for pointing that out.

I just pushed a patch that should do this. It looks at the `date` field first and takes the year of the first date found (i.e., date ranges are ignored). If this fails, then the `year` field is used.

The way the year is extracted from the `date` field may be too simplistic, so do let me know if you run into any trouble.

**Comment by patrl** [comment]
Thank you so much, it's really appreciated! I was considering trying to patch this myself, but I needed a little longer to get a feel for the codebase. Will report back if there are any issues.

**Comment by joostkremers** [comment]
No problem. I want Ebib to handle BibLaTeX well, so something like this is important. I don't use the Date field in my own `.bib` files, though (I probably should...) so it just never occurred to me.
