### ISSUE TITLE
Customising default sorting order

### ISSUE THREAD

**Issue by Knusper** [joostkremers/ebib#121]
First I have to say, thanks for this great emacs package - i just transitioned from jabref, and I really love ebib.   Being an astronomer, I use it in combination with bibslurp -  http://mkmcc.github.io/software/bibslurp.html - and now finally handling my reference database is fun again.

I have customised using the ebib in the following way (excerpt from my .gnu-emacs-custom):

```
 '(ebib-index-columns
   (quote
    (("timestamp" 12 t)
     ("Entry Key" 20 t)
     ("Author/Editor" 40 nil)
     ("Year" 6 t)
     ("Title" 50 t))))
 '(ebib-preload-bib-files (quote ("~/science_works/bibliography.bib")))
 '(ebib-timestamp-format "%Y.%m.%d")
 '(ebib-use-timestamp t)
```

But I want to have descending sort on these timestamps as default, so that my I know that pressing `>` and entering `timestamp` sorts it in the way I like it.  But I don't see an option to have this order as default.

**Comment by joostkremers** [comment]
Thanks, I'm really glad you find Ebib useful. :smiley: 

Up until now it wasn't possible to specify the sort direction and the sort field would automatically be the first field in the index buffer.

I just pushed a fix that changes this. There's a new option `ebib-index-default-sort`, which lets you specify the field to sort on and the sort direction. So in your case you'd probably want to set it

**Comment by joostkremers** [comment]
BTW, I didn't know about Bibslurp. Looks quite cool, but unfortunately I'm in Linguistics, so it's not useful to me. :wink:

**Comment by Knusper** [comment]
So I just installed v. 2.12 from melpa -  and yes, this is exactly what I was looking for.

**Comment by joostkremers** [comment]
Great!
