### ISSUE TITLE
Incompatibility with emacs-purpose

### ISSUE THREAD

**Issue by leezu** [joostkremers/ebib#128]
Hi @joostkremers, it seems there exists some incompatibility between the https://github.com/bmag/emacs-purpose package and ebib. Starting ebib and loading a bib file works fine. However, once I try to edit a multi-line field such as `annotation` (biblatex), the following error is thrown `purpose--action-function: Lisp nesting exceeds ‘max-lisp-eval-depth’` and no multiline edit buffer is shown. I tried obtaining a backtrace, but emacs would only report an empty backtrace for this error.

Do you have any insight in what the issue could be? I am using the standard configuration of `emacs-purpose` as set up by spacemacs in its default configuration. I have not experienced such issue with any other package, but please let me know if you believe this should be addressed in `emacs-purpose` and I'll report a bug there.

I confirmed that the issue does not occur when the `emacs-purpose` package is not used (disabling the `spacemacs-purpose` layer)

I installed ebib via

```
  (use-package ebib
    :init
    (progn
      (spacemacs/set-leader-keys "oe" 'ebib)
      (setq ebib-bibtex-dialect 'biblatex))
    :config
    (progn
      (evil-set-initial-state 'ebib-index-mode 'emacs)
      (evil-set-initial-state 'ebib-entry-mode 'emacs))
    ))
```

(actually using the proper evil bindings from https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-ebib.el )

**Comment by joostkremers** [comment]
I really can't say if the problem is with Ebib or with purpose, but I would suggest that you bring up this issue with the purpose maintainer as well, since he/she obviously understands buffer display in Emacs much better than I do. When you open an issue, please refer to this issue so I hear about it.

**Comment by leezu** [comment]
Thanks @joostkremers and @bmag for your prompt attention, diagnosis and fixes. I confirmed the changes in `ebib` avoid the infinite recursion, so I'll close this issue.
