### ISSUE TITLE
File field seems to be including only file-search-directories

### ISSUE THREAD

**Issue by godfrey-cw** [joostkremers/ebib#130]
When I hit `e` and edit the file field, I get prompted with my `file-search-directories`, as so (cool):
![screenshot from 2019-03-03 11-40-30](https://user-images.githubusercontent.com/38570962/53700631-30dbf680-3da9-11e9-828c-e6c1a4189a68.png)
Then when I tab complete a bit to get the file I want (like this) 
![screenshot from 2019-03-03 11-41-29](https://user-images.githubusercontent.com/38570962/53700639-4c470180-3da9-11e9-8a8e-c1ca04691602.png) and hit enter a couple times, the file entry that's written is just my `file-search-directory`, not the file I selected before hitting enter. 
![screenshot from 2019-03-03 11-42-23](https://user-images.githubusercontent.com/38570962/53700653-6da7ed80-3da9-11e9-94fa-3251f6ef4948.png)

*Edit*: It almost seems like instead of cutting off the leading `file-search-directory`, it's cutting off everything after it?

**Comment by joostkremers** [comment]
Hi, thanks for pointing out this bug. I did a Very Silly Thing(tm) recently, and this is one of the consequences. :disappointed:

Should be fixed now in commit 4d842a1eec68e08acc9d4d77d7d7c3014d5cd55e.
