### ISSUE TITLE
Can the result ebib-import-file use an absolute path?

### ISSUE THREAD

**Issue by xiangsheng** [joostkremers/ebib#138]
It seems that the result generated by `ebib-import-file` is always a filename (i.e. a relative path of the file relative the `ebib-file-search-dirs`). IMHO, the all thing would be more natural if the result of `ebib-import-file` respects the value of `ebib-truncate-file-names` variable. In other word, if the value of `ebib-truncate-file-names` is nil, `ebib-import-file` will generate an absolute path for the file.

Is it a good idea?

**Comment by joostkremers** [comment]
Yes, that makes sense. I'll change it as soon as I can.

**Comment by joostkremers** [comment]
I just pushed a fix to make sure that `ebib-import-file` honors the setting of `ebib-truncate-file-names`. Let me know if you run into any problems.

Thanks for making this suggestion.

**Comment by xiangsheng** [comment]
Thank you for the hard work! Things seem to go well. I only notice that the resulting absolute path is not fully expanded, i.e. `~` is used for the home directory. Admittedly, it makes essentially no difference. But if I edit the `field` field directly, the path added is fully expanded. So I guess it may be a little better to use the expanded path as the result such that two similar actions can give the same result.

**Comment by joostkremers** [comment]
Yes, of course. Should be fixed now. Thanks for pointing that out!

**Comment by xiangsheng** [comment]
Good job!
