### ISSUE TITLE
ebib-create-org-title doesn’t find year in date field

### ISSUE THREAD

**Issue by svictor9** [joostkremers/ebib#141]
Consider the following entry
```
@book{leroi-gourhan2005,
title = {Dictionnaire de la Préhistoire Moderne et Contemporaine},
author = {Leroi-Gourhan, André},
publisher = {Presses universitaires de France},
date = 2005,
address = {Paris},
pagetotal = 1277,
series = {Quadrige}
}
```
Generating a notes file on this entry in ebib (with key N) inserts the following org header : "Leroi-Gourhan, André (????): Dictionnaire de la Préhistoire Moderne et Contemporaine"

`ebib-bibtex-dialect` is set to "biblatex".

I don’t know if this is related to the bug in bibtex.el discussed in [https://github.com/joostkremers/ebib/issues/136](#136) As I understand [line 1360](https://github.com/joostkremers/ebib/blob/b9ba639108c809adac0a632b3f0c8e27548970ee/ebib-utils.el#L1360) in `ebib-create-org-title`, the function only queries the year field.  When I change "year" for date on that line the date is correctly retrieved for the org header, but it is not parsed for its year part (ebib just uses the whole field, which might include month, day, intervals etc.).

**Comment by joostkremers** [comment]
This issue is not related to issue #136, because `ebib-create-org-title` just gets its info from the database directly. There is actually a function already that checks the `date` field, which is used to fill the index buffer. It can be used to create the Org title as well, so I pushed a fix to do that. Let me know if you run into any trouble.

**Comment by svictor9** [comment]
It works now. Thanks!

**Comment by joostkremers** [comment]
Great! Thanks for pointing out this issue. :slightly_smiling_face:
