### ISSUE TITLE
ebib-notes-display-note-symbol: Wrong type argument: stringp, (ebib--update-entry-buffer t)

### ISSUE THREAD

**Issue by hitswint** [joostkremers/ebib#148]
When run ebib for the first time, such error dispalys. but no errors for the second time.
After some investigation, the ebib--notes-buffer should return the notes buffer, but the last form of the function is a add-hook. Some adjustments needs to be made to fix the problem.

**Comment by joostkremers** [comment]
Hmm, that's a very stupid bug. Thanks for reporting it and figuring out where the problem lies.

I just pushed commit a3d19d5, which should fix this. Let me know if you run into further trouble.

**Comment by hitswint** [comment]
Problem solved. Thanks a lot!
