### ISSUE TITLE
Cannot quit entry buffer in 'index-only mode

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [joostkremers/ebib#151]
The buffer complains that it cannot delete the only window in the frame (which is a popup frame). The way to delete the window, more compatible with what *Help* or *info* buffers do, is to use (quit-window). Thus

```
(defun ebib-quit-entry-buffer ()
 [...]
  (cond
   ((and ebib-popup-entry-window
         (eq ebib-layout 'index-only))
    (quit-window))
 [...]
```

**Comment by joostkremers** [comment]
One day I'll have to really learn everything there is to know about window management in Emacs... For now, though, I'll just trust your judgment and make the change you suggest. :smiley:

**Comment by juanjosegarciaripoll** [comment]
Thanks! I have some other suggestions but will try to formulate them more
clearly on separate issues.
