### ISSUE TITLE
hang with global-writeroom-mode on and ebib-reading-list-file not open.

### ISSUE THREAD

**Issue by tshu-w** [joostkremers/ebib#152]
Hi, thanks for your awesome packages! However my emacs hangs when I open ebib with global-writeroom-mode on and ebib-reading-list-file not opened.
here is my ebib config:
```emacs-lisp
(use-package ebib
  :ensure t
  :init
  (setq ebib-default-directory "~/Documents/Zotero"
        ebib-bib-search-dirs '("~/Documents/Zotero")
        ebib-preload-bib-files '("references.bib")
        ebib-notes-file "~/Documents/Zotero/notes.org"
        ebib-reading-list-file "~/Documents/Org/reading_list.org"
        ebib-index-columns '(("Entry Key" 20 t)
                             ("Author/Editor" 40 t)
                             ("Year" 6 t)
                             ("Title" 50 t))
        ebib-use-timestamp t
        ebib-index-default-sort '("timestamp" . descend)
        ebib-file-associations '(("pdf")))
  :general
  (tyrant-def "ae" 'ebib))
```
emacs version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.4.0, Carbon Version 162 AppKit 1894.4) of 2020-03-27
ebib version: 20200327.1040
writeroom mode: 20200303.2331

**Comment by tshu-w** [comment]
I try to add all `ebib*-mode` to `writeroom-major-modes-exceptions` but it doesn't work.

**Comment by joostkremers** [comment]
Did you try to adding `"ebib.*"` to `writeroom-major-modes-exceptions`? (That is, use a regular expression?)

If I try to start Ebib with `global-writeroom-mode` active, Emacs (27) crashes on me...

I'm afraid I don't have much time to look into this right now, so I can't promise I'll be able to fix it soon. For the moment, the best I can suggest is probably not to use `global-writeroom-mode`... :disappointed:

**Comment by tshu-w** [comment]
@joostkremers Yes, I have tried to add "ebib.*" to writeroom-major-modes-exceptions, this doesn't help. writeroom-mode can center the content of the emacs, I love it so much. However, it doesn't matter when you fix it since I can override ebib to to open ebib-reading-list-file before call it. Last but not least, thank for your quick reply and this awesome packages.

**Comment by tshu-w** [comment]
If someone meets this issue too, you can use the following code to fix it temporary.
```emacs-lisp
  (defun ebib@before (&optional FILE KEY)
    "fix crash if `ebib-reading-list-file' is set but not opened."
    (when ebib-reading-list-file
      (find-file-noselect ebib-reading-list-file)))
  (advice-add #'ebib :before #'ebib@before)
```

**Comment by tshu-w** [comment]
It seems like if set `writeroom-maximize-window` nil, this issue disappears.

**Comment by joostkremers** [comment]
> It seems like if set `writeroom-maximize-window` nil, this issue disappears.

That makes sense. The option tries to delete all windows except the selected one, but Ebib requires more than one window to be visible.

Thank you very much for figuring this out! I will change the default value of this option to `nil` and add a warning that setting it is not compatible with `global-writeroom-mode`.
