### ISSUE TITLE
Not possible to enter new publishers

### ISSUE THREAD

**Issue by polemistes** [joostkremers/ebib#153]
After updating ebib, it became impossible to enter more than the first word of a publisher not already in the database. When pressing space, I just get [no match].

**Comment by joostkremers** [comment]
Hmm, I never noticed that because I don't use Emacs default completion system. (I use ivy instead).

I'm pushing a commit that should fix this. If you continue to run into trouble, please
let me know.

Thanks for reporting this issue.
