### ISSUE TITLE
ebib-quit-entry-buffer (C-c b rebound in ebib-mode)

### ISSUE THREAD

**Issue by lockywolf** [joostkremers/ebib#156]
Hello and thank you for your excellent tool!

As far as I understand, C-x b is rebound in ebib-mode so that the buffer with ebib-index-mode is automatically focused.

This doesn't work, however, if the buffer containing ebib-index-mode is killed, or otherwise hidden. C-x b fails and it is therefore impossible to leave ebib-mode.

I would like to ask to either remove the binding (as it is the most common Emacs binding, and it is very confusing to have it perform something unexpected), or, potentially, rebind it to a function which would restore the original two-window frame configuration before switching (this is roughly how (gdb-restore-windows) works.

**Comment by joostkremers** [comment]
> As far as I understand, C-x b is rebound in ebib-mode so that the buffer with
ebib-index-mode is automatically focused.

It depends. In the index buffer it's by default bound to `ebib-leave-ebib-windows`, which, depending on the setting of `ebib-layout`, should either hide the Ebib windows from view or select a non-Ebib window.

In the other buffers (entry, strings, and log buffer), `C-x b` is bound to the same function that `q` is bound to, i.e., it should always leave the buffer and switch back to the index buffer. That's probably the binding you're referring to, I guess?

> This doesn't work, however, if the buffer containing ebib-index-mode is killed, or otherwise hidden. C-x b fails and it is therefore impossible to leave ebib-mode.

Ok, I see what you mean. Normally, the index buffer shouldn't be killed and its window shouldn't be removed, but if it does happen, this is annoying, I agree.

Perhaps the best solution would be to first try what Ebib does now, i.e., switch back to the index window, but if that fails, execute whatever the user has normally bound `C-x b` to.

**Comment by joostkremers** [comment]
> Perhaps the best solution would be to first try what Ebib does now, i.e., switch back to the index window, but if that fails, execute whatever the user has normally bound `C-x b` to.

I've implemented this now, hopefully it works for you as expected.

I'm still considering your suggestion to remove the local binding for `C-x b` completely. I originally added that binding because Ebib kind of assumes that both its buffers are visible and unpredictable things would happen when they are not. But I've since added fixes to mitigate this, so perhaps it's safe to give `C-x b` its default binding back.

The fix I just pushed still makes sense if I do, however, because the relevant function is not only bound to `C-x b` but also to`q`.

**Comment by lockywolf** [comment]
Thank you for considering this! I'll try to test it today.

**Comment by lockywolf** [comment]
Oh, could you also update the melpa package? (I don't know how much of work is that, unfortunately. If it's too much, no need.)

**Comment by joostkremers** [comment]
> Oh, could you also update the melpa package? (I don't know how much of work is that, unfortunately. If it's too much, no need.)

That happens automatically, but not immediately. It usually takes an hour or two, sometimes longer, for new commits to make it to Melpa.
