### ISSUE TITLE
Clicking below the last field in the ebib buffer creates an empty buffer.

### ISSUE THREAD

**Issue by lockywolf** [joostkremers/ebib#162]
This is now it looks like:

![image](https://user-images.githubusercontent.com/2077025/84523337-bf5c5900-ad0a-11ea-9e22-49f9294a2933.png)

The buffer is called "nil". I didn't dig into in deep enough, but it seems that there is some "extra entry" below the last one.

**Comment by joostkremers** [comment]
There is an empty line at the end of the buffer. If you move point with the keyboard, Ebib makes sure not to leave point at that line, but there was no such precaution when using the mouse.

I've pushed a fix for this. Let me know if you still encounter problems.

Thanks for reporting this!
