### ISSUE TITLE
Copy files into subfolders (collections)

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#166]
I'd like to be able to import files and have them moved to a the default folder, maybe named after the first tag in use ... in zotero I can have have collections be created as sub folder into which files are moved (can't remember if it's zotero or the zotfile extension that's doing it). 

Question is how to go about doing something similar with 'ebib'?

**Comment by joostkremers** [comment]
There's a command `ebib-import-file`, which does something like this for the current entry. It's not on any key by default, but it's in the menu and you can call it with `M-x`. There's some machinery behind it to rename the file based on the entry key. The manual has the details (see "Viewing and Importing Files"). If you have any particular suggestions for improvements, I'd be happy to hear them.

**Comment by oatmealm** [comment]
Thanks. I wasn't aware that this is what the function does. I'll give it a try.

**Comment by oatmealm** [comment]
I now remember having a look at it... my problem was not wanting to have everything in one folder... is there a way to move files and make ebib aware of the change, or a priori, maybe use first keyword, for example, as a subfolder...?

**Comment by joostkremers** [comment]
If the folders you're targeting are subfolders of one particular folder, then yes, it's doable. There is an option `ebib-name-transform-function` which points to a function that modifies the target file name. You can actually add a directory before the name, which should be a subdirectory in `ebib-file-search-dirs`. You'd have to write some Elisp to achieve this, however.
