### ISSUE TITLE
Invalid function: helm-build-sync-source

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#168]
I'm seeing this error when trying to `ebib-insert-citation` into org. Ebib is open and there are couple of entries showing.

`helm-M-x-execute-command: Invalid function: helm-build-sync-source [2 times]`

<pre><details>
Doom v2.0.9 (bf9042327c576a96751da78d335f18ced21e111e)
Emacs v27.1
Branch: develop
Build date: 2020-08-06 00:32:36 -0400
---
Ebib version is 2.25
</details></pre>

**Comment by joostkremers** [comment]
Do you have an up-to-date version of helm? Do you have helm installed when you install (compile) Ebib? `helm-build-sync-source` is part of `helm` and it doesn't seem to be the case that it's been removed recently.

I don't use `helm` myself, so I can't really test this part of Ebib. Any hints or help would be very much appreciated.

**Comment by oatmealm** [comment]
Hi @joostkremers ... Yes. I do. I'm using a up-to-date version on `helm` (Using doom-emacs). I'm still seeing this message.

**Comment by joostkremers** [comment]
You need to install Ebib after installing helm. `helm-build-sync-source` is actually a macro, so Emacs needs to know its definition when compiling any code that uses it.

It should suffice to simply uninstall and reinstall Ebib, given that you have helm installed.

**Comment by oatmealm** [comment]
Thanks. It works. I made sure `ebib` loads after helm. I have this now in doom emacs:

```
(use-package! ebib
  :after evil helm
  :commands (ebib)
```
