### ISSUE TITLE
Wrong use of completing-read

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [joostkremers/ebib#169]
`ebib-read-entry-single` uses `completing-read` and assumes that the output of the function is the string with the original properties. This is not true for Emacs' default completion scheme, which returns a fresh new string without properties. This breaks the 'j' command to jump to an entry.

**Comment by joostkremers** [comment]
I noticed this problem with `completing-read-multiple`, but when I tested with `completing-read`, things seemed to work fine. I'll have to look into this a bit further, but it might be a few days before I get to that.

**Comment by joostkremers** [comment]
I've pushed a fix for this issue, contributed by a user. If any problems pop up, please let me know.

**Comment by juanjosegarciaripoll** [comment]
Thanks!
