### ISSUE TITLE
ebib-import url: certification validation failed

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#170]
When trying to use `ebib-import-url` I'm seeing this message. As you can see, I'm accessing JSTOR via a proxy. I'm not sure what's causing the problem.

```
Certificate validation failed www-jstor-org.elib.openu.ac.il, verification code 42
```

In a related note, is there a way to force this redirection via the institutional proxy rather than providing it manually?

**Comment by joostkremers** [comment]
I can't really help here, I'm afraid. Ebib simply uses Emacs' built-in functionality to open external URLs, so that's probably where you need to look for answers. If you mean the function `ebib-download-url` (there's no `ebib-import-url`), then the function to look at is `url-copy-file`.

**Comment by oatmealm** [comment]
Yes, I meant `ebib-download-url`... luckily it seem to work now , at least for one record in ebib with a link which I've tried so far...
Thanks
