### ISSUE TITLE
org export with ebib links

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#171]
As per the information presented in: Links and Citations in Org buffers... how do I export such files via ox-pandoc and get proper. This setup works form me using pandoc style citation [@xxx]... but not with ebib links.

```
#+bibliography: /home/uri/Nextcloud/Library/refrences.bib
#+pandoc_options: filter:pandoc-citeproc:pandoc-docx-pagebreakpy
#+pandoc_options: csl:~/.csl/chicago-note-bibliography-with-ibid.csl reference-doc:~/Nextcloud/Documents/10510/10510-template.docx
#+pandoc_metadata: page-progression-direction:rtl lang:he
```

**Comment by joostkremers** [comment]
The problem is that Ebib links aren't really citations. It would be possible to do what you want, but it would require writing additional functions that handle the conversion.

The Org maintainers are working on getting native citation support into Org, and when it's there, Ebib will support that. Until then, it's probably easiest to customize `ebib-citation-commands` so that you can insert Pandoc-style links into you Org documents.

**Comment by oatmealm** [comment]
Ok. I switched to inserting with ```bibtex-completion``` since I had it already setup... I looked at ```ebib-citation-commands``` but wasn't sure how to update the `org-mode` sub-list to add and `pandoc` style command.... :( should I simply re-define it? I like the idea that it will let me choose the command, i.e. pandoc style, or "cite" etc...

<details><pre>
((latex-mode
  (("cite" "\\cite%<[%A]%>[%A]{%(%K%,)}")
   ....)
 (org-mode
  (("ebib" "[[ebib:%K][%D]]")))
 (markdown-mode
  (("text" "@%K%< [%A]%>")
   ("paren" "[%(%<%A %>@%K%<, %A%>%; )]")
   ("year" "[-@%K%< %A%>]"))))
</pre></details>

**Comment by oatmealm** [comment]
Ok, replaced the 'ebib' key in the alist like so. Replaced the defailt for org-mode since I figured I'm not going to use ebib links in org in any case:

```
  (map-put ebib-citation-commands 'org-mode '((("pandoc" "[@%K%< [%A]%>]"))))
```

**Comment by joostkremers** [comment]
Perhaps it makes sense to copy the config for `markdown-mode` to `org-mode`:

```
  (map-put ebib-citation-commands 'org-mode '((org-mode
                                               (("text" "@%K%< [%A]%>")
                                                ("paren" "[%(%<%A %>@%K%<, %A%>%; )]")
                                                ("year" "[-@%K%< %A%>]")))))
```

That would make it possible to use all three citation formats that Pandoc recognizes.

**Comment by oatmealm** [comment]
Thanks! I ended up doing this, but keeping ebib links, turned out to be useful after all in some cases, even if not exportables :)

```
  (map-put ebib-citation-commands 'org-mode '(("text" "@%K%< [%A]%>")
                                              ("paren" "[%(%<%A %>@%K%<, %A%>%; )]")
                                              ("year" "[-@%K%< %A%>]")
                                              ("ebib" "[[ebib:%K][%D]]")))
```

Would be nice though to have a specifier like %C to use when needed, with org links of the format ebib:XXX as well as cite:XXXX ... I find the option to link to an ebib record directly useful ...

**Comment by joostkremers** [comment]
> Would be nice though to have a specifier like %C to use when needed, with org links of the format ebib:XXX as well as cite:XXXX ... I find the option to link to an ebib record directly useful ...

This, too, should be doable, but it would take some setting up. The file `org-ebib.el` defines the `ebib` link type in Org mode. You'd have to do something similar for the other link types.

**Comment by oatmealm** [comment]
Just to say that it's easier to simply add to 'ebib-citation-commands 'org-mode like so, without overriding the package's default....

```
(push (cons "cite" "cite:%K, [%A]")
        (car (alist-get 'org-mode ebib-citation-commands)))
```
