### ISSUE TITLE
Search only works from current record forward

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#173]
It seems like when performing a search (`ebib-search`) it is only performed from current active record in the index list onwards. Need to repostion to the begining of the index and search again.

```
‘women and islam’ not found.  [g] to jump to top, [left]/[right] to search previous/next database.
```

**Comment by joostkremers** [comment]
Yes, that's how it works. That's the reason why I added the key binding `g` to the search keymap: you can simply press `g` and then `RET` to search for the next match.

I rarely use this search functionality myself, so perhaps it's not ideal. I'm open to suggestions for improvements. I usually use `j` (`ebib-jump-to-entry`) together with `ivy`, which allows me to search for author/editor, title and year, which is what I search most of the time. For keyword searches I tend to use filters.

**Comment by oatmealm** [comment]
I'm realising that many of the key on ebib's various key-maps are shadowed and I'm missing functionality... sorry about the confusion. `ebib-jump-to-entry` is great!
