### ISSUE TITLE
Copy record key

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#175]
Is there a simple way to copy just the key, unformatted, from the index or record view? I know I can S+e to edit it, but is there a shortcut?

I went through the amazingly useful tutorial 👍 but I don't see that's possible.

**Comment by joostkremers** [comment]
Nope, there isn't. Seems like I need to implement a copy function that will let users copy various pieces of information in various ways. Shouldn't be too hard. :smiley:
