### ISSUE TITLE
Multiple attachment files

### ISSUE THREAD

**Issue by goderich** [joostkremers/ebib#178]
I am using a biblatex database exported from Zotero. Some entries have multiple attachments. There are several cases where having multiple attachments under a single entry would make more sense:

- Main paper plus supplementary materials,
- Multiple versions of the same paper (e.g. preprint and journal version; different languages; long vs short version),
- Chapterized dissertations/books.

Right now Ebib appears to always assume one attachment per entry. When an entry has multiple attachments, it just prints out the names of the files and does nothing else.

Is this something that should be resolved in Ebib itself, or in users' individual configs? I believe that ideally if there's only one attachment, Ebib should open it immediately, but if there are several, it should prompt the user to choose one.

The only problem I can see with this is that there are potentially many ways in which multiple files can be written into a single entry in bibtex/biblatex.

**Comment by joostkremers** [comment]
I assume you are talking about the `file` field, right? There can be multiple files in it, but Ebib needs to know how they are separated. The default separator is `"; "` (semicolon-space), but you can customise it. The option is called `ebib-filename-separator`.

Note that when you press `e` on the `file` field to edit it, you'll be prompted for a file name. If you want to change the separator, that won't work. Instead, you can edit the field with `C-u e`.

**Comment by goderich** [comment]
Thank you for the excellent tool and for the quick response!

I see now that Ebib does exactly this already, just that my separator was ";" without the space. Apologies for the false alarm!
