### ISSUE TITLE
Manually setting the citation key on entry

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#179]
Hope I'm not missing the point here, but it seems like the citation key can be edited 
 only after a new record was added. Ie 'q' from the new entry form and then 'E' to expose the key and possibly manually change it? That's my workflow at least. 

Since I tend to use custom citation keys, I was wondering if it'd possible to expose the key in the entry form so it can be edited when a new record is added...?

In zotero it can be done via BetterBibLatex adding "Citation key:" in the notes field.

**Comment by joostkremers** [comment]
There's currently no way to edit the key in the entry buffer (perhaps there should be), but if you unset the option `ebib-autogenerate-keys`, you will be asked for a citation key when you add a new entry manually.

**Comment by oatmealm** [comment]
I think that's a reasonable solution.
