### ISSUE TITLE
Support biblio's doi-insert-bibtex

### ISSUE THREAD

**Issue by oatmealm** [joostkremers/ebib#181]
I know that `ebib` supprts yanking bibtex definitions from the clipboard, so was hoping I could also use `biblio.el`'s `doi-insert-bibtex`... error is: 

```
ebib-edit-field: Wrong type argument: number-or-marker-p, nil
```
https://github.com/cpitclaudel/biblio.el/blob/2809afa121234405997edd6650ed600d6cc0545a/biblio-doi.el#L112
```
(defun doi-insert-bibtex (doi)
  "Insert BibTeX entry matching DOI."
  (interactive "MDOI: ")
  (let ((target-buffer (current-buffer)))
    (biblio-doi-forward-bibtex
     (biblio-cleanup-doi doi)
     (lambda (result)
       (biblio-doi--insert
        (biblio-format-bibtex result biblio-bibtex-use-autokey)
        target-buffer)))))
```

**Comment by joostkremers** [comment]
A quick look suggests that this function places a BibTeX entry in the current buffer, right? That wouldn't work with Ebib, because yanking a BibTeX definition from the kill ring in Ebib doesn't simply yank it into the entry buffer. What you'd need to do is to do `doi-insert-bibtex` into a temp buffer and call `ebib-import` afterwards. So something like this (untested):

```
(defun ebib-biblio-insert-doi (doi)
  "Insert BibTeX entry matching DOI using biblio.el."
  (interactive "MDOI: ")
  (with-temp-buffer
    (doi-insert-bibtex doi)
    (ebib-import)))
```

**Comment by oatmealm** [comment]
Just got around to test this. I'm seeing:

```
Error while processing request: (buffer-read-only #<buffer  1:references.bib>)
```

**Comment by joostkremers** [comment]
Hmm, it seems that `biblio` fetches the BibTeX entry asynchronously by default, which means that in the above snippet, Ebib tries to import an entry that isn't there yet. Adding a `(sleep-for 5000)` after the call to `doi-insert-bibtex` should make it work, but the extra wait would be annoying, of course.

`biblio` is designed to be extensible, so I think the best way would be to add an action to biblio's selection menu that stores the current entry in the current Ebib database. I'm currently trying to find out how to do that.

**Comment by joostkremers** [comment]
Oh, I just noticed that `doi-insert-bibtex` is different: it doesn't show the selection buffer, it inserts the entry into the current buffer directly.

**Comment by joostkremers** [comment]
Well, the simplest way is of course to temporarily force biblio to fetch entries synchronously:

```
(defun ebib-biblio-insert-doi (doi)
  "Insert BibTeX entry matching DOI using biblio.el."
  (interactive "MDOI: ")
  (with-temp-buffer
    (let ((biblio-synchronous t))
      (doi-insert-bibtex doi)
      (ebib-import)
      (message "Done"))))
```

The synchronous setting is only active when `ebib-biblio-insert-doi` is called, so it won't change your config permanently.

All in all, though, it's probably better to use `biblio-doi-forward-bibtex` directly. I'll need to look at the code a bit to find out how to use it properly.

**Comment by joostkremers** [comment]
Ok, this seems to work:

```
(defun ebib-import-doi (doi)
  "Import entry matching DOI into the current database."
  (interactive "MDOI: ")
  (biblio-doi-forward-bibtex
   (biblio-cleanup-doi doi)
   (lambda (result)
     (with-temp-buffer
       (biblio-doi--insert
        (biblio-format-bibtex result biblio-bibtex-use-autokey)
        (current-buffer))
       (ebib-import-entries)))))
```

I actually tested it, though not extensively.

**Comment by joostkremers** [comment]
I just added support for biblio.el to Ebib itself. Details are discussed here:

https://joostkremers.github.io/ebib/ebib-manual.html#integration-with-the-biblio-package

**Comment by oatmealm** [comment]
The biblio+ebib integration works vert well for me. The only thing I'd suggest (if at all possible) is to re-center the ebib index to the new entry, or maybe yank the key or title, so it's easy to immediately `ebib-jump-to-entry`, the way `ebib-import-doi` (which works too!).

Also, I think I see that duplicates in both are handled by the fact that it generates the same key?

![gnome-shell-screenshot-TX4L10](https://user-images.githubusercontent.com/68159077/115114372-3f88c600-9f8f-11eb-94c8-9ed2cc1f8f7b.png)


This is so helpful. Thanks a lot.

**Comment by joostkremers** [comment]
> The biblio+ebib integration works vert well for me. The only thing I'd suggest (if at all possible) is to re-center the ebib index to the new entry, or maybe yank the key or title, so it's easy to immediately `ebib-jump-to-entry`, the way `ebib-import-doi` (which works too!).

I'll have to take a closer look here. Internally, `ebib-biblio-selection-import` and `ebib-biblio-import-doi` use the same mechanism to add an entry to the current database, so I'm not sure why you are seeing a difference. It may have to do with window management.

> Also, I think I see that duplicates in both are handled by the fact that it generates the same key?

Currently, yes. Which means you need to configure both Ebib and Biblio to generate the same keys. (Ebib uses `bibtex.el` for that and Biblio does as well, I think, so that shouldn't be too difficult.)

Perhaps I should let Ebib check for duplicates using the DOI as well.

**Comment by cpitclaudel** [comment]
Just came across ebib — excellent stuff @joostkremers! :)  And I'm very happy to see the synergies with biblio.  Let me know if there's any thing I can do on the biblio side to make your life easier!

**Comment by joostkremers** [comment]
@cpitclaudel Thanks! If anything comes up, I will let you know!
