### ISSUE TITLE
Unknown entry type "review" and "audio"

### ISSUE THREAD

**Issue by sati-bodhi** [joostkremers/ebib#184]
I've got the following warning when loading my ebib database: 

```
20 Oct 2020, 00:59:17: Opening file /Users/satibodhi/Creation/notes/bibliography/thesis.bib
Line 2903: Unknown entry type `review'.
Line 14323: Unknown entry type `audio'.
Line 14336: Unknown entry type `audio'.
Line 14349: Unknown entry type `audio'.
Line 14362: Unknown entry type `audio'.
1916 entries, 0 @Strings and no @Preamble found in file.
Using general keyword list.
```
But according to the biblatex manual, these are supposed to be valid reference types. 

![圖片](https://user-images.githubusercontent.com/7592695/96488106-17363e00-1270-11eb-99aa-bcd586ea9f4e.png)

![圖片](https://user-images.githubusercontent.com/7592695/96488033-02f24100-1270-11eb-9d74-2d1ffb12946b.png)

 Is this a bug?

**Comment by joostkremers** [comment]
Ebib simply uses the entry types defined by `bibtex.el`, and indeed, `Review` and `Audio` are not there. You can add them yourself by customising `bibtex-biblatex-entry-alist`.
