### ISSUE TITLE
[FEATURE] A new option or function to use relative file path in reading list instead of absolute one

### ISSUE THREAD

**Issue by Vonfry** [joostkremers/ebib#185]
`ebib-create-org-file-link` calls `ebib--expand-file-name` which use `expand-file-name` and `locate-file` to return an absolute file path. Someone may want to use a relative one.

**Comment by joostkremers** [comment]
Should Ebib then honour `org-link-file-path-type`, or would a separate Ebib-specific customisation option be preferable?
