### ISSUE TITLE
The copied reference contains "{Journaltitle|Journal}" when there is "&" in the journal name

### ISSUE THREAD

**Issue by fountainer** [joostkremers/ebib#187]
If the entry is as follows:

```
@article{kourtis2012parameter,
	title = {Parameter uncertainty in portfolio selection: Shrinking the inverse covariance matrix},
	author = {Kourtis, Apostolos and Dotsis, George and Markellos, Raphael N},
	journal = {Journal of Banking \& Finance},
	volume = {36},
	number = {9},
	pages = {2522--2531},
	year = {2012},
	publisher = {Elsevier}
}
```

The copied reference is `Kourtis, Apostolos and Dotsis, George and Markellos, Raphael N (2012). "Parameter uncertainty in portfolio selection: Shrinking the inverse covariance matrix". Journal of Banking {Journaltitle|Journal} Finance, 36, 2522--2531. `. 

The symbol `\&` is missing and there is an additional item `{Journaltitle|Journal} `.

**Comment by joostkremers** [comment]
There was a bug in the function that fills the template with data from the entry. It should be fixed now.

Thanks for reporting this!

**Comment by fountainer** [comment]
Thanks. It works as expected now.

**Comment by joostkremers** [comment]
:+1: I'll close this issue then.
