### ISSUE TITLE
Ebib - customizing type field in entry buffer

### ISSUE THREAD

**Issue by Richard-CAID** [joostkremers/ebib#190]
I recently found reference to ebib and gave it a try - awesome!

I require a few extra type fields in the entry buffer. I modified ebib-reference-templates (see below) and dropped into in dotspacemacs user-config (emacs 27.1 running on opensuse.). That did not thing. I have gone through ebib manual a couple of times and searched through ebib, biblio, and bibtex-completion *.el files but also found nothing to help.

How do I add 2 new types for the type field in the entry buffer?  - Richard

(setq ebib-reference-templates '(
        ("Article"                 . "({Date|Year}) {Author}, {\"Title\".} {Journaltitle|Journal}, {Volume}{:Issue}, {Pages}. {Doi|Url.}")
        ("Book"                   . "({Date|Year}) {Author|Editor}, {\"Title\".} {Publisher.} {Doi|Url.}")
        ("MvBook"              . "({Date|Year}) {Author|Editor}, {\"Title\".} {Publisher.} {Doi|Url.}")
        ("InBook"                . "({Date|Year}) {Author}, {\"Title\".} In: {Editor}, {\"Booktitle\"}. {Publisher.} {Pages.} {Doi|Url.}")
        ("Collection"            . "({Date|Year}) {Editor}, {\"Title\".} {Publisher.} {Doi|Url.}")
        ("MvCollection"       . "({Date|Year}) {Editor}, {\"Title\".} {Publisher.} {Doi|Url.}")
        ("InCollection"         . "({Date|Year}) {Author}, {\"Title\".} In: {Editor}, {\"Booktitle\"}. {Publisher.} {Pages.} {Doi|Url.}")
        ("Misc"                    . "({Date|Year}) {Author|Editor}, {\"Title\".} {Howpublished.}")
        ("Court"                   . "({\"Title\".}")
        ("Correspondence" . "({Date|Year}) {Howpublished}, {\"Title\".} {Note.}")
        ("Online"                 . "({Date|Year}) {Author|Editor}, {\"Title\".} {Organization.} {Doi|Url.}")
        ("Proceedings"       . "({Date|Year}) {Editor}, {\"Title\".} {Organization.}")
        ("MvProceedings"  . "({Date|Year}) {Editor}, {\"Title\".} {Organization.}")
        ("InProceedings"    . "({Date|Year}) {Author}, {\"Title\".} In: {Editor}, {\"Booktitle\"}. {Publisher.} {Pages.} {Doi|Url.}")
        ("Thesis"                . "({Date|Year}) {Author}, {\"Title\".} {Type,} {Institution.} ")
        ("Unpublished"       . "({Date|Year}) {Author}, {\"Title\".} {Howpublished.} {Note.}")))

**Comment by joostkremers** [comment]
Ebib uses the entry types defined in `bibtex.el`, so that's where you need to look. It's mentioned in the manual in the section "Opening a .bib file", though it's easy to overlook. (Writing a good manual is much harder than programming, I find... :slightly_smiling_face: )

So basically you need to customize `bibtex-biblatex-entry-alist` or `bibtex-BibTeX-entry-alist`, depending on whether you use biblatex or BibTeX (I highly recommend biblatex).

`ebib-reference-templates` is only used when you copy a reference to the kill ring. You'll need to customize it if you use `ebib-copy-reference-as-kill` (see the section "Copying Entries to the Kill Ring and System Clipboard" in the manual).

`biblio` and `bibtex-completion` are separate packages, I don't know if and how they deal with custom entry types, you'd have to check their documentation.

**Comment by Richard-CAID** [comment]
I appreciate your response. I did notice a reference to bibtex.el in your manual. However, a search of my .emacs.d folder showed no bibtex.el. Adding bibtex to my .spacemacs-configuration-layers brings in org-ref, bibtex-completion, biblio and biblio-core. The lack of a bibtex.el containing package suggests a change in emacs 27.1 for bibliographies. I did attempt to download a copy of bibtex.el but did not locate one to glean out what I needed. 

I am still a newbie with emacs and have rudimentary elisp understanding. So, drawing lines between bibtex-biblatex-entry-alist and what that may be in .el files in the 4 27.1 packages is not easy.

Can you point me in a correct direction?

**Comment by Richard-CAID** [comment]
FYI, there is a bracket problem with ebib-reference-templates proceedings and MvProceedings with Date|year. {(Dater|Year}) should be ({Date|Year}) if I understand my syntax.

**Comment by joostkremers** [comment]
> FYI, there is a bracket problem with ebib-reference-templates proceedings and MvProceedings with Date|year. {(Dater|Year}) should be ({Date|Year}) if I understand my syntax.

And in `Proceedings` and `Online`, as well, I notice. Fixing it now.
