### ISSUE TITLE
Full tree visualisation in note window

### ISSUE THREAD

**Issue by Richard-CAID** [joostkremers/ebib#193]
Can notes be displayed to include all headings starting with the upper most heading of a note with ebib-notes-open-after-hook?
I discovered a note display can be used to edit notes and refiled with org-capture. When ebib functions with multiple notes files capable of multiple entries (assuming ":Custom_id:" is included in PROPERTIES), access to an entry's full tree will provide a simple platform for refiling.

**Comment by joostkremers** [comment]
I'm not sure, there may be an Org function that does that. Perhaps the Org mailing list can help?

**Comment by Richard-CAID** [comment]
I am building my database from scratch and so am flexible at this point. I will take this as, no ebib cannot have its custom_id in a PROPERTIES drawer under, for example, a level 3 headline and display a "note" with its 2 higher level headlines. I will build around this.

**Comment by joostkremers** [comment]
Note that when you customise `ebib-notes-open-note-after-hook` and remove the function `org-narrow-to-substree`, you'll at least see the entire Org document, not just the note. Perhaps that helps?

**Comment by Richard-CAID** [comment]
PROPERTIES searches in orgmode bring up the headline level with the PROPERTIES drawer that a property is found in. This holds true in Ebib notes as well. So, the limitation appears to be in orgmode. I appreciate your help on this though. (Removing org-narrow-to-subtree did not help.)
