### ISSUE TITLE
Question: how should ebib-index-open-at-point work?

### ISSUE THREAD

**Issue by dalanicolai** [joostkremers/ebib#197]
I am not sure if I missed something, but when I try to open some entry from the index, nothing happens. Looking at the source of
`ebib-index-open-at-point` I find it is looking for a link with text property of `'mouse-face` or `'help-echo` (or otherwise for a note), but none of the entries seem to have such text-property. 

So my questions are:
- how is `ebib-index-open-at-point` supposed to work?
- is there some function to visit a file directly from the index?

Obviously, I could not find any answers easily...

Thanks for the very nice package, it already looks great!

**Comment by joostkremers** [comment]
The function `ebib-index-open-at-point` opens links in the index buffer when clicked with the mouse. The point is, however, that by default, there are no links in the index buffer... :slightly_smiling_face:  If you add the `"Doi"`, `"Url"` or `"Note"` field to the columns displayed in the index buffer, you'll get clickable links. See the manual, section [The Entries List](http://joostkremers.github.io/ebib/ebib-manual.html#the-entries-list), for details.

In the index buffer, you can use `f` to open a file in the `"File"` field of the current entry, `I` (capital `i`) to open the DOI in the `"Doi"` field and `u` to open a URL in the `"Url"` field. Perhaps those are the commands you're looking for?

**Comment by dalanicolai** [comment]
I discovered `ebib-view-file` just now (from [this manual](https://mirror.las.iastate.edu/tex-archive/biblio/bibtex/utils/ebib/doc/html/ebib-manual.html#sec12)). I was searching for the terms 'find' or 'open'. Anyway, I did not find this option/function in the 'official' manual, but the function is there. Thanks again for this beautiful package!

**Comment by dalanicolai** [comment]
These were really simultaneous comments. Indeed those were the functions I I was looking for. Actually, Ivy/helm-bibtex are really useful for this too. Thank you for your answer...

**Comment by joostkremers** [comment]
> I discovered `ebib-view-file` just now (from [this manual](https://mirror.las.iastate.edu/tex-archive/biblio/bibtex/utils/ebib/doc/html/ebib-manual.html#sec12)). I was searching for the terms 'find' or 'open'. Anyway, I did not find this option/function in the 'official' manual, but the function is there. Thanks again for this beautiful package!

That's a really old version of the manual! The corresponding section in the current version is [here](http://joostkremers.github.io/ebib/ebib-manual.html#viewing-and-importing-files).

I realise the current HTML version of the manual isn't easy to navigate, because it's long and there is no menu. I intend to change this, hopefully soon! An alternative is the info manual available in Emacs itself (if you installed the package through Melpa, it should be there).

**Comment by joostkremers** [comment]
> Actually, Ivy/helm-bibtex are really useful for this too.

Yes, and there's nowadays also [bibetx-actions](https://melpa.org/#/bibtex-actions), which does the same thing for selectrum.

**Comment by dalanicolai** [comment]
Ah, I did not notice that I was not searching in the manual (I was quickly searching with C-f on [the ebib homepage](http://joostkremers.github.io/ebib/), but on first sight it looks exactly like the manual.
I discovered selectrum before via the mentioning on your page. It looks like something I would prefer to use (i.e. a more clean/integrated version of helm/ivy). But I am using Spacemacs where it is not very straightforward to switch to Selectrum because Spacemacs core is largely build around helm/ivy. Luckily, both helm and ivy are great packages too...

**Comment by joostkremers** [comment]
> Ah, I did not notice that I was not searching in the manual (I was quickly searching with C-f on [the ebib homepage](http://joostkremers.github.io/ebib/), which on first sight looks exactly like the manual).

Hmm, that's a good point. Perhaps I should really differentiate the two visually. I'll keep that in mind when I redesign the website.

**Comment by dalanicolai** [comment]
> > I discovered `ebib-view-file` just now (from [this manual](https://mirror.las.iastate.edu/tex-archive/biblio/bibtex/utils/ebib/doc/html/ebib-manual.html#sec12)). I was searching for the terms 'find' or 'open'. Anyway, I did not find this option/function in the 'official' manual, but the function is there. Thanks again for this beautiful package!
> 
> That's a really old version of the manual! The corresponding section in the current version is [here](http://joostkremers.github.io/ebib/ebib-manual.html#viewing-and-importing-files).
> 
> I realise the current HTML version of the manual isn't easy to navigate, because it's long and there is no menu. I intend to change this, hopefully soon! An alternative is the info manual available in Emacs itself (if you installed the package through Melpa, it should be there).

When you bulid a new website, I would really recommend you to check out [org-thtml](https://juanjose.garciaripoll.com/blog/org-mode-html-templates/index.html). I think it not very well known yet, but it is a great package. It think it is not explicitly mentioned anywhere, but on [its github page], there is a `make.el` file in the personal-site folder. You can just follow it and it will create a website for you. The templating system makes the website extremely flexible...

**Comment by dalanicolai** [comment]
> > I discovered `ebib-view-file` just now (from [this manual](https://mirror.las.iastate.edu/tex-archive/biblio/bibtex/utils/ebib/doc/html/ebib-manual.html#sec12)). I was searching for the terms 'find' or 'open'. Anyway, I did not find this option/function in the 'official' manual, but the function is there. Thanks again for this beautiful package!
> 
> That's a really old version of the manual! The corresponding section in the current version is [here](http://joostkremers.github.io/ebib/ebib-manual.html#viewing-and-importing-files).
> 
> I realise the current HTML version of the manual isn't easy to navigate, because it's long and there is no menu. I intend to change this, hopefully soon! An alternative is the info manual available in Emacs itself (if you installed the package through Melpa, it should be there).

When you bulid a new website, I would really recommend you to check out [org-thtml](https://juanjose.garciaripoll.com/blog/org-mode-html-templates/index.html). I think it is not very well known yet, but it is a great package. It think it is not explicitly mentioned anywhere, but on [its github page], there is a `make.el` file in the personal-site folder. You can just follow it and it will create a website for you. The templating system makes the website extremely flexible...

**Comment by joostkremers** [comment]
> When you bulid a new website, I would really recommend you to check out [org-thtml](https://juanjose.garciaripoll.com/blog/org-mode-html-templates/index.html). 

The input file for the manual is in Markdown, so I've been relying on Pandoc to convert it to texinfo, and it's easiest for me to use Pandoc for html output as well...

Anyway, the new website is now live, **with** a TOC, so hopefully things will be easier to find now.

**Comment by dalanicolai** [comment]
That makes sense when the source file is in Markdown.
The new site looks good and very clear to me (although somehow I really liked the nice colors on the previous version). Thanks for the update!

**Comment by joostkremers** [comment]
Thanks for your feedback. It's true, the new colours are rather, well, minimalistic... I agree the old theme looked nice, but I must admit I was getting a bit tired of it. I'll probably throw in some more colours once the minimalism of the current site starts boring me, though. :smile:
