### ISSUE TITLE
Cannot install ebib-biblio: "Package ‘ebib-biblio-’ is unavailable"

### ISSUE THREAD

**Issue by antipodite** [joostkremers/ebib#209]
Hi, thanks for this useful package. Jabref seems to introduce worse and worse bugs every update so great to have ebib to fall back on.

Following the instructions in the ebib docs, I tried to install ebib-biblio thus:
`(use-package ebib-biblio
  :after (ebib biblio)
  :bind (:map biblio-selection-mode-map
              ("e" . ebib-biblio-selection-import)))`

However, when I `C-x C-e` I get the following error message:

`Error (use-package): Failed to install ebib-biblio: Package ‘ebib-biblio-’ is unavailable`

Any ideas on how I could fix this?

**Comment by antipodite** [comment]
Never mind I figured out `require` is the way to go

**Comment by joostkremers** [comment]
Sorry for the late reply (I was on vacation), glad you got it  fixed.
