### ISSUE TITLE
Add keyword to marked entries

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/ebib#21]
Adding the same keyword to different entries one at a time is very inefficient. Entries can be marked and using the prefix an action can be applied to all marked entries.

Now [it is possible](https://gist.github.com/mardukbp/6513819) to add a keyword to all marked entries. Just press `;y`.

**Comment by scottmartincampbell** [comment]
This bit of code also sounds great, but don't seem to work with the latest ebib (2015-01-02). Would it be hard to update it?

**Comment by joostkremers** [comment]
This will require a bit of work. As indicated above, I meant to merge the code but never got round to it... I'll put it back on my todo list and hopefully this time I won't forget.

**Comment by scottmartincampbell** [comment]
Thanks! I'll test the timestamp filter code and keep an eye on this other one.

**Comment by joostkremers** [comment]
I've added the function to Ebib, the new version should appear in Melpa in a few hours. The function (bound to `y`) can add keywords to a single entry from the index buffer, and also to multiple marked entries, with `; y`.

Let me know if any problems turn up.

**Comment by scottmartincampbell** [comment]
That works great! Thanks a bunch. I'm really enjoying using ebib. 

Scott

**Comment by joostkremers** [comment]
Note, in the latest update, I changed the key binding for this command to `K a`. Also, it's no longer necessary (or ever possible) to use the semicolon prefix. If there are marked entries, `K a` will automatically add keywords to all of them.
