### ISSUE TITLE
How to set ebib-index-default-sort option?

### ISSUE THREAD

**Issue by fountainer** [joostkremers/ebib#212]
I want to sort entries on "Year" in descending order. I used the following setting, but it didn't work.

```emacs-lisp
(setq ebib-index-default-sort '("Year" "descend"))
```
Is this option set in this way?

**Comment by joostkremers** [comment]
No, the second element should be a symbol, like so:

```emacs-lisp
(setq ebib-index-default-sort '("Year" descend))
```

I admit, that's not clearly stated in the manual...

**Comment by joostkremers** [comment]
Sorry, let me correct that; it should be a cons cell:

    (setq ebib-index-default-sort '("Year" . descend))
    
(Note the dot between `"Year"` and `descend`).

**Comment by fountainer** [comment]
> Sorry, let me correct that; it should be a cons cell:
> 
> ```
> (setq ebib-index-default-sort '("Year" . descend))
> ```
> 
> (Note the dot between `"Year"` and `descend`).

Thanks. It works.

**Comment by joostkremers** [comment]
I've added a note to the manual explaining the format of this variable.
