### ISSUE TITLE
Proposal: Do not ask to kill the viewer process when emacs is closed

### ISSUE THREAD

**Issue by nils-schween** [joostkremers/ebib#219]
Hi,

I very often open my books by searching for them with ebib and then typing "f". I noticed that emacs always tells me that all my open pdfs will be closed when I quit emacs. Normally, I do not want this to happen. 

The pdf viewer is started in the function `ebib--call-file-viewer` by callling the lisp routine `start-process`. I was wondering if it made sense to replace the `start-process` call with  a `call-process` call. 
If `call-process` is invoked with the right arguments, the pdf viewer is started as a separate process and not as subproces of emacs. Hence the pdf viewer stays alive, when emacs is closed (https://www.emacswiki.org/emacs/ExecuteExternalCommand#h5o-10)

I temporarily replaced the `start-process` call with a `call-process` call in `ebib--call-file-viewer`:
```elisp
;; (start-process (concat "ebib " ext " viewer process") nil viewer file-full-path))
(call-process viewer nil 0 nil file-full-path))
```
This works. But there are of course more places where a call to `start-process` is made. In case of opening the browser, I am not sure if this replacement made sense at all. And I do not know if the proposed change has any undesirable side effects.

Do others have the same problem? And is such a change a good idea?
Nils

**Comment by joostkremers** [comment]
Ok, I made the change, it seems to work fine in the little testing I did. Let me know if you run into any issues, though. And let's hope no-one complains. :slightly_smiling_face:
