### ISSUE TITLE
Feature request: No warnings for @jurisdiction and @legislation

### ISSUE THREAD

**Issue by Quintus** [joostkremers/ebib#227]
Dear all,

I am a researcher in German law (i.e., a kind of jurist) and use Ebib to maintain my bibliographic Biblatex database. I have lots of entries of type `@jurisdiction` (court decisions) and some of `@legislation` (documents from the parliamentary process of creating laws), which Ebib currently does display, but only with warnings:

~~~~~~~
...
13 Nov 2021, 11:02:26: Line 478: Unknown entry type `Jurisdiction'.
13 Nov 2021, 11:02:26: Line 490: Unknown entry type `Jurisdiction'.
13 Nov 2021, 11:02:26: Line 829: Unknown entry type `Jurisdiction'.
13 Nov 2021, 11:02:26: Line 839: Unknown entry type `jurisdiction'.
13 Nov 2021, 11:02:27: Line 1641: Unknown entry type `Legislation'.
13 Nov 2021, 11:02:27: Line 1649: Unknown entry type `Legislation'.
...
~~~~~~~

This is on Ebib 2.32.2 from MELPA.

These entries look like this:

~~~~~ bibtex
@Jurisdiction{bgh2013usedsoft-ii,
  author       = {BGH},
  type         = {Urteil},
  number       = {I ZR 129/08},
  eventdate    = {2013-07-17},
  shortjournal = {GRUR},
  journaltitle = {Gewerblicher Rechtsschutz und Urheberrecht},
  year = {2014},
  pages = {264-272},
  title     = {UsedSoft II},
  commentator = {Malte Stieper}
}

@Jurisdiction{eugh2021topsystem,
  author       = {EuGH},
  type         = {Urteil},
  number       = {C-13/20},
  eventdate    = {2021-10-06},
  title        = {Top System/Belgien}
}

@legislation{bt12-4022,
author = {{Deutscher Bundestag}},
title = {Entwurf eines Zweiten Gesetzes zur Änderung des Urheberrechtsgesetzes},
number = {BT-Drs. 12/4022},
date = {1992-12-18}}

@legislation{kom1988-816,
author = {{EG-Kommission}},
title = "Vorschlag für eine Richtlinie des Rates über den Rechtsschutz von Computerprogrammen",
number = "KOM(1988) 816 endg.",
date = "1989-01-05"}
~~~~~

It would be nice if Ebib would not log warnings for them. Biblatex does contain these types (Biblatex manual § 2.1.3). I also intend to use the type `@commentary` mentioned there, but haven't done so much yet.

**Comment by joostkremers** [comment]
Hi,

Ebib uses the entry and field definitions from `bibtex.el`. These are customisable, so you can add `@jurisdiction` and `@legislation` yourself. Either customise the option `bibtex-biblatex-entry-alist` or add the relevant values in your init file. Once they are defined, Ebib shouldn't complain about them anymore and should also be able to display the required, optional and extra fields correctly.

**Comment by Quintus** [comment]
Ah indeed, you are right. My bad. I got confused while switching from my own written-from-scratch citation system to org's new citation functionality; the customisation of `bibtex-biblatex-entry-alist` was in the files for my own system. Since I also updated from Debian 10 to 11 and pretty much all software I use I suspected a problem there.

Anyway, thanks, my bad.

**Comment by joostkremers** [comment]
> Anyway, thanks, my bad.

Hey, no worries.
