### ISSUE TITLE
Symbol’s function definition is void: nil after ff93a3

### ISSUE THREAD

**Issue by tshu-w** [joostkremers/ebib#233]
Hi, I got following error after commit ff93a31f7e979e5e478a37c5d1e0e65b5bd7b4dc
```
Debugger entered--Lisp error: (void-function nil)
  nil(#("2021-10-22 10:37:42 (CST)" 0 25 (ebib--xref nil)) #("2021-11-18 21:36:09 (CST)" 0 25 (ebib--xref nil)))
  #f(compiled-function (cl-x cl-y) #<bytecode -0x73c6e589dfdee29>)((#("2021-10-22 10:37:42 (CST)" 0 25 (ebib--xref nil)) . "johnson_emacs_2021") (#("2021-11-18 21:36:09 (CST)" 0 25 (ebib--xref nil)) . "azzalini-21-block-techn-entit-linkag"))
  cl-sort(((#("2021-11-18 21:36:09 (CST)" 0 25 (ebib--xref nil)) . "azzalini-21-block-techn-entit-linkag")) nil :key car)
  cl-stable-sort(((#("2021-11-18 21:36:09 (CST)" 0 25 (ebib--xref nil)) . "azzalini-21-block-techn-entit-linkag")) nil :key car)
  ebib--sort-keys-list(("johnson_emacs_2021") ((entries . #<hash-table equal 2/65 0x1fe3621b8343>) (strings) (preamble) (comments) (local-vars) (dialect) (buffer . #<buffer misc.bib>) (cur-entry) (marked-entries) (filter) (sortinfo) (filename . "/Users/wangtianshu/Documents/Bibliography/misc.bib") (main) (keys) (modtime 25016 36207 850753 792000) (modified) (backup . t)))
  ebib--list-keys()
  ebib--update-index-buffer(no-refresh)
  ebib--update-buffers(no-refresh)
  ebib()
  funcall-interactively(ebib)
  command-execute(ebib)
```

GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H1519)) of 2021-12-14

**Comment by joostkremers** [comment]
Hi, it's difficult to tell from the backtrace where the problem lies, exactly, so I'll need to ask a few questions.

First, just to be sure: did you try restarting Emacs after upgrading Ebib? Sometimes when upgrading a package in a running session, you end up using a mix of old and new code.

If that's not it, could you tell me the value of the variables `ebib-index-columns` and `ebib-field-sort-functions-alist`? If either of these values is incorrect, it could explain the result you're seeing.

**Comment by tshu-w** [comment]
1. Yes, I bisect the issue commit and rebuild and restart every time.
2. both `ebib-index-columns` and `ebib-field-sort-functions-alist` are default value:
```
(("Entry Key" 40 t)
 ("Author/Editor" 40 t)
 ("Year" 6 t)
 ("Title" 50 t))
```
```
(("Chapter" . ebib-compare-numerical-strings)
 ("Sortyear" . ebib-compare-numerical-strings)
 ("Volume" . ebib-compare-numerical-strings)
 ("Volumes" . ebib-compare-numerical-strings))
```

**Comment by tshu-w** [comment]
I found I got this error by setting `ebib-index-default-sort '("timestamp" . descend)`

**Comment by joostkremers** [comment]
> I found I got this error by setting `ebib-index-default-sort '("timestamp" . descend)`

Thank you, that was an important clue. I never considered the possibility that one could sort the index buffer on a field value that is not shown in the index buffer (i.e., is not listed in `ebib-index-columns`).

I now know what causes the bug and I hope to push a fix out tonight. Thanks for reporting this.

**Comment by joostkremers** [comment]
This should be fixed now.
