### ISSUE TITLE
Symbol’s function definition is void: dbus-byte-array-to-string

### ISSUE THREAD

**Issue by Jousimies** [joostkremers/ebib#245]
GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-27

ebib version is 4aed0c3, Update doc string of `ebib--expand-strings`.

Open ```ebib```, echo the error 
```ebib--expand-string: Symbol’s function definition is void: dbus-byte-array-to-string```

**Comment by joostkremers** [comment]
Hmm, does the problem go away if you load `dbus.el`? To test, do `M-x ielm RET` and type `(require 'dbus)` at the prompt, followed by `RET`. Then try to start Ebib again.

If that doesn't work, then perhaps you have a version of Emacs compiled without dbus support (if that is even possible, I don't know.)

@Hugo-Heagren In light of this problem and the one reported in #242 I think it would be better to disable string expansion by default and let the user decide if they want to enable it. At least until these issues can be solved.

@Jousimies I'll push a commit shortly that should make Ebib functional again for you.

**Comment by Hugo-Heagren** [comment]
> @Hugo-Heagren In light of this problem and the one reported in #242 I think it would be better to disable string expansion by default and let the user decide if they want to enable it. At least until these issues can be solved.

Good call. I've made a PR with a (very simple!) fix.
