### ISSUE TITLE
Email PDF with mu4e/gnus

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/ebib#25]
Sometimes I need to send a paper to a colleague or student, for example, in advance of our journal club meeting. Since I manage both my email and my papers in emacs, it seemed natural to me to have the possibility to attach the corresponding PDF file while writing the message.

I [implemented](https://gist.github.com/mardukbp/6576377) this and tested it with mu4e but it's very likely that it will work with gnus out of the box.

**Comment by joostkremers** [comment]
Moved to the wiki: <https://github.com/joostkremers/ebib/wiki>.
