### ISSUE TITLE
Melpa install of ebib fails with `http://stable.melpa.org/packages/ebib-2.25.1.tar: Not found`

### ISSUE THREAD

**Issue by balajis** [joostkremers/ebib#254]
# Problem
The ebib tar file appears to be missing from melpa.org, so melpa install doesn't work.

# Detail
To reproduce the issue, open up emacs and then:
`M-x package-install <RET>`
`ebib <RET>`

You get the following error:
`http://stable.melpa.org/packages/ebib-2.25.1.tar: Not found`

Here's a screenshot of the minibuffer:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/10866/169041757-d922596d-0ef4-4ea5-b911-999067497485.png">

**Comment by joostkremers** [comment]
In my experience this is usually caused by your local package list not being up to date. Try updating your package list and see if the problem persists.
