### ISSUE TITLE
Import bibtex from journal's website

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/ebib#26]
As a follow-up to [Zotero-like arXiv integration](https://github.com/joostkremers/ebib/issues/23) here is the corresponding code for importing a paper's citation in bibtex format directly from the journal's website.

[Here](https://gist.github.com/mardukbp/6576418) is `ebib-import-bibtex`. Place [this](https://gist.github.com/mardukbp/6576427) file in `~/.conkerorrc`. Enjoy!

**Comment by joostkremers** [comment]
Moved to the wiki: <https://github.com/joostkremers/ebib/wiki>.
