### ISSUE TITLE
Unknown entry type `video'

### ISSUE THREAD

**Issue by Cletip** [joostkremers/ebib#266]
Hello
Everything is in the title. 
this happens when an entry is of the following form: 
```
@video}{fields...
}
```
I think ebib just doesn't recognize the videos.

**Comment by joostkremers** [comment]
The entry types and fields used by Ebib are those defined in `bibtex.el`, which is part of Emacs. There's a user option you can customise, though I can't look up what it's called right now, as I'm on mobile.

**Comment by Cletip** [comment]
I see exactly what a mistake this is. I will report it, I will keep up to date here.
Thanks for the answer !

**Comment by Hugo-Heagren** [comment]
I think the user option you're looking for is `bibtex-biblatex-entry-alist` or `bibtex-BibTeX-entry-alist` (note that the first is all lowercase, the second is not).
