### ISSUE TITLE
Question: customization of buffer containing ref details

### ISSUE THREAD

**Issue by AlainGuill** [joostkremers/ebib#274]
Dear Joost, 
I really like ebib. You already helped me some times ago to organize a buffer with my keywords. This time I'm wondering whether it's possible to force the order of the field of the buffer appearing below the list of references ?
For me it would be great to have always the same order : "title, authors, keywords, journal"
Is it already possible and I'm missing something ?
Thanks a lot by advance.
Alain

**Comment by joostkremers** [comment]
The order is determined by the user option `bibtex-BibTeX-entries-alist` or `bibtex-biblatex-entry-alist`, so you'd have to customise these to get the effect you want.

Note, though, that those user options are organised according to the type of field. The doc string has the details, but basically required and optional fields are separated, and the order of fields in Ebib reflects this.

In Ebib, the distinction isn't used for much else, so I don't think it would result in any inconveniences if you use your preferred order. I don't know what problems may arise with `bibtex.el` itself, though, if you also edit your `.bib` files by hand.

**Comment by AlainGuill** [comment]
Thank you so much for this answer (and sorry for being so late to write). Unfortunately I tries several times to change it in my init.el but without sucess. Would it be possible for you to show how you can change it? Thanks again for your answer and your time

**Comment by AlainGuill** [comment]
Hello, I finally managed to have what I wanted. I think I was not trying correctly. 
'(bibtex-BibTeX-entry-alist
   '(("Article" "Article in Journal"
      (("keywords")
       ("author"))
      (("title")
       ("journaltitle")
       ("shortjournal")
       ("year"))
      (("abstract")
       ("volume")
       ("number")))
etc... for the other format ("InProceedings", "Conference", ...)
Thanks a lot for your help ! Alain
