### ISSUE TITLE
Symbol's function definition is void: object-intervals

### ISSUE THREAD

**Issue by tsdye** [joostkremers/ebib#275]
Line 507 of ebib.el.

This one popped up after an upgrade a few days ago.  Ebib is unusable now because the entries don't show.  The keys are there, but I don't see the entries.

**Comment by Hugo-Heagren** [comment]
Just had a look at this -- it was introduced by my PR #268. `object-intervals` only appeared in emacs 28.1 (I'm on 29), but presumably  you're using an earlier version.

**Comment by Hugo-Heagren** [comment]
@joostkremers we could:
- use [compat.el](https://github.com/emacs-compat/compat) (probably my preferred solution)
- rewrite the orignal using only supported functions -- the only problem with this is that it will be significantly more complex code (`object-intervals` does exactly what we need, and there isn't really an obvious replacement idiom from earlier) and would slow things down a fair bit (`object-intervals` is written in C, so is fast, whereas any alternative would be a complex function in elisp, probably built with `cl-loop`, which is a heavy macro)

What do you think?

**Comment by tsdye** [comment]
Hugo-Heagren ***@***.***> writes:

> Just had a look at this -- it was introduced by my PR #268. 
> object-intervals only appeared in emacs 28.1 (I'm on 29), but 
> presumably you're using an earlier version.

Yes, I'm using emacs 27.1.

--
Thomas S. Dye
https://tsdye.online/tsdye

**Comment by joostkremers** [comment]
The manual for compat.el says that it doesn't provide `objects-interval`, so unfortunately, using compat won't solve the issue. :disappointed:

**Comment by joostkremers** [comment]
I apologise for this mishap, I should have checked for compatibility issues before merging the Xdata functionality.

@Hugo-Heagren, is there a possibility of making the Xdata functionality version-dependent? In particular, would it be possible to isolate all the relevant code in a separate file `ebib-xdata.el`, which could then be `require`d with `noerror` set to `t`?

I generally try to keep compatibility with two previous Emacs versions, so even though Emacs 29 is to be released soon, Emacs 27 should still be supported.

**Comment by Hugo-Heagren** [comment]
I've put up some fix code, which I think should work for older emacs. Sorry again about this.

> is there a possibility of making the Xdata functionality version-dependent?
I think this would be quite difficult to do. I also think that new features should be available to everyone if they can be (and this one can)!

> In particular, would it be possible to isolate all the relevant code in a separate file ebib-xdata.el, which could then be required with noerror set to t?

In particular, the answer to this is no. The Xdata code is just too much a part of the general database-access code. I think my fix above works though, so hopefully everything will be fine.

**Comment by tsdye** [comment]
Joost Kremers ***@***.***> writes:

> Closed #275 as completed via #276.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

Ebib works again.  Thanks!

All the best,
Tom
-- 
Thomas S. Dye
https://tsdye.online/tsdye
