### ISSUE TITLE
Don't uniquify already unique keys

### ISSUE THREAD

**Issue by leinfink** [joostkremers/ebib#277]
If `ebib-uniquify-keys` is non-nil, `ebib-generate-autokey` on an entry that currently has a unique key will produce a new unique key by adding or changing the alphabetical postfix.

This is unexpected if that is the only change between the old and new key. I think the expected behavior would be to keep the old key if the new key would differ only (unnecessarily) in the uniquified postfix. That is, using `ebib-generate-autokey` on a key with a _different_ format, e.g., a default key like `<new-entry>`, should of course still return a new key even if the old key was already unique.

**Comment by joostkremers** [comment]
Thanks for reporting this. It seems like a bug. I'll try and find a fix for it as soon as I have some time.

**Comment by joostkremers** [comment]
Well, it took a while, but I finally had a look and fixed this issue. Thanks for reporting it.

**Comment by leinfink** [comment]
Wonderful, thanks!
