### ISSUE TITLE
Completion fields customization

### ISSUE THREAD

**Issue by jabotz** [joostkremers/ebib#278]
The manual says that I can customize the user option `ebib-edit-fields-functions`. But when I try to customize it, I get an error.

Here's the sequence. Run `emacs -Q` (Windows 11). Then: `M-x ebib RET` Ebib panes appear, no bibtex buffer loaded. `M-x customize-option RET ebib-field-edit-functions RET`. In the lower third pane I see the usual emacs customization interface: "For help using this buffer, see Easy Customization in the Emacs manual. Operate on all settings in this buffer." But there are no settings to modify. In the minibuffer the message is: "Wrong type argument: listp, "Fields" "

My purpose is to make the _address_ field to be completed (like the _author_ field, for example). What am I doing wrong?

**Comment by Hugo-Heagren** [comment]
Just had a look. The `:tag` argument in the customisation type was in the wrong place. #279 should fix it.

**Comment by joostkremers** [comment]
Yes, @Hugo-Heagren , that's the correct diagnosis. I just merged your fix.\

Thanks for the report and the quick fix! And apologies for the late reply. :disappointed:
