### ISSUE TITLE
`ebib-add-keywords-to-entry` and `ebib-edit-current-field` do not generate the same list of completion candidates

### ISSUE THREAD

**Issue by benthamite** [joostkremers/ebib#280]
Thank you for creating and maintaining this package. It has become an integral part of my workflow.

I noticed that the list of candidate keywords available for completion differs depending on whether I run `ebib-add-keywords-to-entry` or `ebib-edit-current-field` (with point on the `keywords` field). Specifically, only when I do the former do I see all the keywords I define in `ebib-keywords`. By contrast, running the latter only displays the keywords present in any of the existing entries.

Let me know if this suffices to reproduce the issue; otherwise, I’d be happy to provide more details.

**Comment by joostkremers** [comment]
Hi, thanks for reporting this (and apologies for the late reply). You are right, the two functions use different methods to collect the candidate list for completion. I'll see about a way to fix this.

**Comment by joostkremers** [comment]
I have pushed a commit that should fix this issue.

**Comment by benthamite** [comment]
Great, thank you!
