### ISSUE TITLE
ebib crashes on recursive crossref fields

### ISSUE THREAD

**Issue by ghost** [joostkremers/ebib#281]
MWE:

```
@{Article}{<new-entry1>,
	crossref = {<new-entry1>},
	note = {This is a test note that is here for testing purposes.},
	title = {Test Title},
	author = {Test Author}
}
```
a reference which references itself makes ebib go into an infinite loop.

**Comment by joostkremers** [comment]
Hmm, yeah, I guess this is a case I never considered... Shouldn't be too hard to fix. I'll push an update soon.

Thanks for reporting this.

**Comment by joostkremers** [comment]
I pushed a fix for this, and with the example entry you provide, Ebib doesn't go into an infinite loop any more.
