### ISSUE TITLE
How to add hidden fields?

### ISSUE THREAD

**Issue by fountainer** [joostkremers/ebib#282]
I want to hide some fields, e.g, `volume`, `number`, `pages`, `notes`. I tried the following code.

```emacs-lisp
  (push "volume" ebib-hidden-fields)
```
However, the `volume` filed is still in the entry buffer.  How should I use the `ebib-hidden-fields`?

**Comment by joostkremers** [comment]
The code should work, but I suspect you don't see its effect because it's executed too early. Wrapping it inside a `with-eval-after-load` should do the trick:

``` emacs-lisp
(with-eval-after-load 'ebib
  (push "volume" ebib-hidden-fields))
```

**Comment by fountainer** [comment]
I put the `(push "volume" ebib-hidden-fields)` in the `:config` section in `use-package`. It does not work. I also try the code
```
(with-eval-after-load 'ebib
  (push "volume" ebib-hidden-fields))
```
The issue still exists. I checked the value of `ebib-hidden-fields`
```
("volume" "addendum" "afterword" "annotator" "archiveprefix" "bookauthor" "booksubtitle" "booktitleaddon" "chapter" "commentator" "edition" "editora" "editorb" "editorc" "eid" "eprint" "eprintclass" "eprinttype" "eventdate" "eventtitle" "foreword" "holder" "howpublished" "introduction" "isbn" "isrn" "issn" "issue" "issuesubtitle" "issuetitle" "issuetitleaddon" "journaltitleadddon" "journalsubtitle" "language" "location" "mainsubtitle" "maintitle" "maintitleaddon" "month" "origlanguage" "pagetotal" "part" "primaryclass" "remark" "subtitle" "timestamp" "titleaddon" "translator" "urldate" "venue" "version" "volumes")
```

**Comment by joostkremers** [comment]
Note that hidden fields are still shown when they have a value.  There is currently no mechanism to hide fields when they have a value.
