### ISSUE TITLE
Ebib 2.39.4 does not display my database anymore

### ISSUE THREAD

**Issue by Knusper** [joostkremers/ebib#284]
I just got a new machine, and I installed the latest ebib from melpa stable.
I also ensured to install parsebib from melpa stable.  

My configuration is the following:

```
(use-package ebib
  :ensure t
  :pin melpa-stable
  :config
  (setq ebib-index-columns
	(quote
	 (("timestamp" 12 t)
	  ("Entry Key" 20 t)
	  ("Author/Editor" 40 nil)
	  ("Year" 6 t)
	  ("Title" 50 t))))
  (setq ebib-index-default-sort (quote ("timestamp" . descend)))
  (setq ebib-index-window-size 28)
  (setq ebib-preload-bib-files (quote ("~/science_works/bibliography.bib")))
  (setq ebib-timestamp-format "%Y.%m.%d")
  (setq ebib-use-timestamp t)
  (setq ebib-uniquify-keys t)
  )
```

When I open ebib only the first entry (correctly sorted by timestamp) is displayed in the list. Nothing is displayed in the entry buffer.

I get the following message:
`ebib--display-entry-key: Symbol’s function definition is void: pos-bol`

For now I roll back to 2.35.1 (this I had on my laptop now for ages and it works fine).  Thanks for all your work on ebib, it is very essential for my work.

**Comment by joostkremers** [comment]
Oh... That's a major SNAFU from my side... `pos-bol` is a new function in Emacs 29, and since I want to support older versions of Emacs, I should not have used it at all...

I'll push a fix for it as soon as possible.

**Comment by joostkremers** [comment]
I added a dependency on the `compat` library, which provides `pos-bol` for older Emacsen. Could you try it (version 2.39.5) and see if it works? Thanks!

**Comment by Knusper** [comment]
I'll give it a try tonight.

**Comment by joostkremers** [comment]
I've pushed a few more commits (not related to this issue), so the latest version is 2.40.

**Comment by Knusper** [comment]
I am a bit confused, because these new commits do neither appear in melpa or melpa stable.  I will install it manually then, but maybe something is not working correctly?

**Comment by joostkremers** [comment]
Yes, I messed up the `Package-Requires:` header... Since that's a comment, compiling the file locally wasn't a problem, but Melpa extracts the contents and tries to parse it, which failed.

I pushed a commit to fix it. During the next build round Ebib should build again.

**Comment by Knusper** [comment]
Finally found time to test this.  Ebib now works flawlessly with emacs 27.1
