### ISSUE TITLE
Using ebib in conjunction with oscola or jura. How to add entry types to ebib.

### ISSUE THREAD

**Issue by anoduck** [joostkremers/ebib#285]
I am trying to use biblatex and [oscola-bibtex](https://github.com/PaulStanley/oscola-biblatex) to create a legal reference library. How do I add the entrytypes from oscola to ebib, so that I can use ebib to add entries?

**Comment by joostkremers** [comment]
The entry types that Ebib uses are those defined by `bibtex-mode`, and they can be customised in the user option `bibtex-biblatex-entry-alist`.

**Comment by anoduck** [comment]
@joostkremers Thanks! I just discovered how to add entry types to bibtex mode about two or three hours ago. Super sweet ebib will just pick them up from there. Makes life much easier. Brilliant programming. 

Modifying them in the custom interface adds all the entry designations to my init, so I might just use a `add-to-list` to put them there. 

Awesome sauce! Thanks for answering my question.

**Comment by anoduck** [comment]
@joostkremers I got it fully configured and working now. Holy SnapDragons! This is so convenient.
