### ISSUE TITLE
Problems with adding keywords -- C-M-j does not finish

### ISSUE THREAD

**Issue by scfrank-pri** [joostkremers/ebib#290]
K calls "Add keyword (C-M-j to finish) []"
But C-M-j does not finish the selection, instead it shrinks the whole frame by a few lines, vertically. I am confused by this, because I cannot leave  "Add keyword" - and the frame gets smaller and smaller with each try to finish. 
I double checked with a blank emacs configuration. Turns out that this seems the new standard behavior of "C-M-j". I am using emacs 29.1

**Comment by joostkremers** [comment]
Which completion mechanism do you use? The key in the message "(C-M-j to finish)" should depend on the completion mechanism.

**Comment by scfrank-pri** [comment]
I use swiper/ivy/counsel. But even when I start emacs without any init file, "C-M-j" shrinks the frame.

**Comment by scfrank-pri** [comment]
Here comes the solution. The problem was not caused by emacs or ebib, but by the gnome extension gTile, which has occupied <C-M-j>. I have uninstalled it, and everything works as before.

**Comment by joostkremers** [comment]
Well, I'm glad you found that out, because I never would have...
