### ISSUE TITLE
Highlights for Index and Entry Fields

### ISSUE THREAD

**Issue by lamberta** [joostkremers/ebib#39]
(Regarding a change introduced a few months back, sorry.)

I'm using the [Zenburn theme](http://www.emacswiki.org/emacs/ColorThemeZenburn) (a fairly popular theme, the only reason I bring it up) which has a subtler highlight face than some. In prior ebib versions there was a cursor *and* highlight face to indicate what field you were currently on within the index and entry buffers. Since then, the cursor has been removed leaving only the highlight. The current effect is easier to see within the index buffer since the highlight extends through all columns, however, within the entry buffer, the highlight only affects the single word of the field's first column, which can be rather difficult to see.

Personally, I liked the cursor since it was easy to see and I could jump around the buffer and cut/paste as usual. But if it's gone, perhaps add a dedicated ebib-highlight-face? Or, I'm not sure if there's a way to add a per buffer highlight face to customize? Or, maybe just extending the highlight across all columns (like in the index buffer) will make it more apparent which field is highlighted.

**Comment by joostkremers** [comment]
FYI, the visibility of the cursor has been configurable since commit 74c9c5a, but perhaps you already knew that.
