### ISSUE TITLE
Abstract in several lines

### ISSUE THREAD

**Issue by hc36123** [joostkremers/ebib#47]
Hello. Is there some options to allow the item of 'abstract' in a article to be displayed in multiple lines? I think this could be a great help for me to recall the main idea of a paper quickly. And in the searching process, keywords which should be highlighted in 'abstract' are usual invisible cause the long sentence be omitted.
Thanks.

**Comment by Enrico68** [comment]
I 'fixed' this with `visual-line-mode`

**Comment by hc36123** [comment]
That's just great. And thanks a lot.

**Comment by pipping** [comment]
It might be worth mentioning that `ebib-view-field-as-help` (bound to `v` by default) addresses this rather nicely.

**Comment by Knusper** [comment]
> I 'fixed' this with `visual-line-mode`

Is there a way to set this as 'default' for the ebib-entry buffer?

**Comment by joostkremers** [comment]
> > I 'fixed' this with visual-line-mode

> Is there a way to set this as 'default' for the ebib-entry buffer?

The entry buffer has a dedicated major mode, `ebib-entry-mode`, which comes with its own hook, `ebib-entry-mode-hook`, so it should be a simple matter of doing:

    (add-hook 'ebib-entry-mode-hook #'visual-line-mode)

in your `init.el`.

**Comment by joostkremers** [comment]
The latest Ebib version has the ability to display more than a single line of multiline values. By default, it shows the first 10 lines, but this number can be configured.
