### ISSUE TITLE
Keywords in db don't match keywords in bib file

### ISSUE THREAD

**Issue by scottmartincampbell** [joostkremers/ebib#64]
Not a bug, just a request.

I wrote a short function that allows me to quickly filter just by keyword (see below, if anyone else is interested). However, in doing so I noticed that the set of keywords maintained by ebib and returned by `ebib--keywords-for-database` is not the same as what's in the .bib file, just what has expliclty been added through ebib or are explicitly stored in a keyword file. So, keywords in entries that are imported are not added, nor are those added manually.

So, a request: a function that rebuilds the list of keywords in the database to match those in the file, and could be run occasionally (perhaps when the db is saved to a file)?  To get around this, I can use sed to scrape keywords from the .bib and rewrite the keyword file occasionally, but I couldn't quite get through `ebib-keywords.el` right now to figure it out.
 
```

(defun ebib-filter-keywords ()
  "Creates filters on the fly for keywords"
  (interactive)
  (let* ((keyword-reg (completing-read "Keyword: " (ebib--keywords-for-database ebib--cur-db)  nil nil nil 'ebib--keywords-history)))
    (ebib--execute-when
      ((filtered-db)
       (ebib-db-set-filter `(and ,(ebib-db-get-filter ebib--cur-db) 
				   (contains "keywords" ,keyword-reg)) ebib--cur-db)
       (ebib--redisplay))
      ((real-db)
       (ebib-db-set-filter `(contains "keywords" ,keyword-reg) ebib--cur-db)
       (ebib--redisplay))
      ((default)
       (beep)))))
```

**Comment by joostkremers** [comment]
Hi Scott,

I thought about this issue a bit and decided to do this a bit differently. With the latest update to Ebib, keywords that are not in the keywords file are displayed in red (or whatever your theme defines as the default `error` face). If you spot such keywords, you can use the command `K s` to make them permanent (i.e., store them, so that they get saved to the keyword file when you close the database).

This is not the wholesale approach that you suggested, but I hope you can live with it. :-)

BTW, If you want to write a function yourself, there are one or two new functions in `ebib-keywords.el` that might be of help, esp. `ebib–keywords-to-list` and `ebib–keywords-remove-existing`.

**Comment by scottmartincampbell** [comment]
Hi Joost, 

I'm having a bit of trouble testing this: `ebib-keywords-to-list` started throwing "wrong number of arguments". I've traced it to the fact that I'm using Emacs 24.3, and I'm guessing you use 24.4, which has a new `split-string` which has the new optional TRIM argument you're using. 

Since I'm not ready to upgrade to 24.4, if you're willing to include the `s` library, maybe this line will do? Seems to work. I don't know enough elisp regexp to suggest something native, at least not very quickly.

`(mapcar 's-trim (split-string str (regexp-opt (list ebib-keywords-separator "{" "}")) t)))`

I do like your approach (with 'new' keywords in red) that can be saved when recognized/needed.

**Comment by joostkremers** [comment]
Hi Scott,

Thanks for letting me know about the incompatibility. I've removed the `TRIM` argument to `split-string` for the moment. I think it would still be better to trim them, but I want to remain compatible with Emacs 24.3.

I’ll have to think about using `s-trim`. Loading an entire library for a single function may be a bit overkill, but OTOH `s` is probably quite common now, so most people will have it installed already as a dependency of other packages.

**Comment by joostkremers** [comment]
I've used `replace-regexp-in-string' to trim the strings. Works as well.
