### ISSUE TITLE
Auto-generate keys

### ISSUE THREAD

**Issue by tsdye** [joostkremers/ebib#66]
Aloha Joost,

I'm not able to auto-generate keys with a recent ebib.  I noticed that the manual directs the user to the customization interface to toggle this capability.  I have this in my .emacs:
 (setq ebib-autogenerate-keys t)

Is my setup deprecated?

All the best,
Tom

**Comment by joostkremers** [comment]
Nothing has changed in terms of customisation, so if the `setq` statement worked before, there's no obvious reason why it shouldn't work now. What exactly is happening? Are you asked to provide a key or is a key of the form `<new-entry1>` not converted?

**Comment by tsdye** [comment]
Aloha Joost,

Joost Kremers <notifications@github.com> writes:

> Nothing has changed in terms of customisation, so if the `setq`
> statement worked before, there's no obvious reason why it shouldn't
> work now. What exactly is happening? Are you asked to provide a key or
> is a key of the form `<new-entry1>` not converted?
>

Earlier, a key of the form `<new-entry1>' was not converted, but when I
went back just now (with a new instance of ebib) it all worked as
expected, and I wasn't able to trigger the problem that I saw before.

Also, earlier when I tried to change `<new-entry1>' with `!', which IIUC
replaces the old `K', nothing happened.  When I checked this just now, I
see the same behavior, both when I press `!' and when I do `M-x
ebib-generate-autokey'.  Neither of these seem to work for me.

All the best,
Tom

>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/joostkremers/ebib/issues/66#issuecomment-85734540
> Nothing has changed in terms of customisation, so if the setq
> statement worked before, there's no obvious reason why it shouldn't
> work now. What exactly is happening? Are you asked to provide a key or
> is a key of the form <new-entry1> not converted?
>
> —
> Reply to this email directly or view it on GitHub.
>
>

-- 
T.S. Dye & Colleagues, Archaeologists
735 Bishop St, Suite 315, Honolulu, HI 96813
Tel: 808-529-0866, Fax: 808-529-0884
http://www.tsdye.com

**Comment by joostkremers** [comment]
Hi Tom,

Sorry I never got back to you about your problem.

> Also, earlier when I tried to change `<new-entry1>' with `!', which IIUC
replaces the old `K', nothing happened.  When I checked this just now, I
see the same behavior, both when I press `!' and when I do `M-x
ebib-generate-autokey'.  Neither of these seem to work for me.

Is this still a problem for you?

**Comment by tsdye** [comment]
Aloha Joost,

Not a problem anymore.  You can close this issue.

Thanks for your good work on Ebib.

All the best,
Tom

Joost Kremers <notifications@github.com> writes:

> Hi Tom,
>
> Sorry I never got back to you about your problem.
>
>> Also, earlier when I tried to change `<new-entry1>' with `!', which IIUC
> replaces the old `K', nothing happened.  When I checked this just now, I
> see the same behavior, both when I press `!' and when I do `M-x
> ebib-generate-autokey'.  Neither of these seem to work for me.
>
> Is this still a problem for you? 
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/joostkremers/ebib/issues/66#issuecomment-174690676


-- 
Thomas S. Dye
http://www.tsdye.com

**Comment by joostkremers** [comment]
Thanks for the quick reply. Glad it works now.
