### ISSUE TITLE
Cannot delete field called "Date-Modified"

### ISSUE THREAD

**Issue by brabalan** [joostkremers/ebib#67]
I have an entry that looks like this:

``` bibtex
@book{SangiorgiWalker2001,
	Author = {Sangiorgi, Davide and Walker, David},
	Date-Added = {2011-02-28 10:59:01 +0100},
	Date-Modified = {2011-02-28 10:59:03 +0100},
	Publisher = {Cambridge University Press},
	Title = {The $\pi$-calculus: a Theory of Mobile Processes},
	Year = {2001}
}
```

I'm trying to delete the fields called "Date-Modified" and "Date-Added", but I can't do it from ebib. If I try to do so (hitting 'd' on the field), then it becomes "Date" but the file is not changed.

**Comment by joostkremers** [comment]
Yes, I can confirm the bug. I probably didn't consider the possibility that field names contain dashes. I'll look into it and see about a fix.

**Comment by joostkremers** [comment]
Ok, found the problem. Latest version should fix it.

**Comment by brabalan** [comment]
It works great, thanks.
