### ISSUE TITLE
ebib org-mode links don't open

### ISSUE THREAD

**Issue by mahaha** [joostkremers/ebib#71]
ebib inserts links into org-mode this way: `[[name2001][]]`

Opening that link leads me to the error `no link found`

When I manually remove the outer brackets, so that it reads `[name2001][]` everything works fine.

**Comment by joostkremers** [comment]
Not sure why this is happening. The [orgmode docs](http://orgmode.org/manual/Link-format.html#Link-format) say that links should be of the format `[[link][description]]` and that’s what Ebib inserts.

Note that Emacs needs to be configured for opening Ebib links first:

http://joostkremers.github.io/ebib/ebib-manual.html#consulting-bibtex-databases-outside-ebib

Note, though, that you can customise the links that Ebib inserts:

    M-x customize-option RET ebib-citations-commands RET

And change the link for `org-mode`.

**Comment by mahaha** [comment]
I am using `spacemacs`, if that is of any use. I have since changed the link, but this is very strange behaviour.

**Comment by mahaha** [comment]
I have no changed the link command to output `[[ebib:author2000]]`, so without the description, and that seems to work fine.

**Comment by joostkremers** [comment]
I really have no idea why the standard links that Ebib inserts don't work for you. It works fine on my system (though I don't use Spacemacs, but I doubt that makes any difference...)
