### ISSUE TITLE
Feature request: default file name

### ISSUE THREAD

**Issue by WorldsEndless** [joostkremers/ebib#72]
ebib is great; I use it heavily in conjunction with helm-bibtex (the latter while I'm writing papers, and ebib while I'm studying/reviewing my bibliographies). One of the nice features of helm-bibtex is that, given a default file directory, it it automatically tries to open <<bibtex-key>>.pdf. It would be great if this was the default behavior when trying to open the associated file in ebib, for entries where no file is specified. 

e.g. 

    @article{menig1978, ...

attempts to open pdfdir/menig1978.pdf

**Comment by joostkremers** [comment]
You mean when the `file` field is empty? That's actually a good idea. Shouldn't be too hard to implement.

**Comment by joostkremers** [comment]
It was a very easy fix, sorry I didn't get to it earlier. Should work as desired now.
