### ISSUE TITLE
Problems with preload bib files

### ISSUE THREAD

**Issue by Enrico68** [joostkremers/ebib#73]
Hello,

I am trying to preload bib files without success. I set up correctly the `Ebib Preload Bib FIles` pointing to my bib file in Dropbox, but Ebib starts with empty screen. Even copying the file in my `~`directory does not solve the problem.

**Comment by joostkremers** [comment]
What's the path to your `.bib` file and what is the value of `ebib-preload-bib-files`? To find out the latter, do `C-h v` and type `ebib-prel` followed by TAB, then hit RETURN.

**Comment by Enrico68** [comment]
Joost Kremers <notifications@github.com> writes:

> What's the path to your `.bib` file and what is the value of `ebib-preload-bib-files`? 

The path of my bib file is ~/Dropbox/PDF/ and the value is
~/Dropbox/PDF/Biblio.bib. Anyway I noticed from the mode line that ebib actually load my
file but the screen is blank.

**Comment by Enrico68** [comment]
Joost Kremers <notifications@github.com> writes:


Forgot to mention that I am using evil if this can be related...

**Comment by joostkremers** [comment]
If Ebib shows a blank screen when `ebib-preload-bib-files` is configured, that means it thinks the file is new. So Ebib isn't finding your file.

Really the only thing that can cause this problem is that the file path in `ebib-preload-bib-files` is not identical to the file path of the actual file. Are you absolutely sure that the two are identical?

**Comment by joostkremers** [comment]
`evil-mode` really shouldn't make a difference, but if you want to make sure, start Emacs with `emacs -Q` and load Ebib manually with `M-x load-library RET /path/to/ebib RET`.

**Comment by Enrico68** [comment]
Now it works, (I dont know why, maybe a typo or did not set correctly the variable). Thanks Joost for your patience :-) !

**Comment by joostkremers** [comment]
Glad it works!
