### ISSUE TITLE
Filtering for a set of keys

### ISSUE THREAD

**Issue by kuerzn** [joostkremers/ebib#75]
Hi! Thanks for ebib!

I use org mode and links to ebib to manage and categorize my bibliography. I have written a function that extracts all the Keys of all ebib links in a subtree. How can I limit my database to only show these keys?

The simplest and bad-hack solution I found after a first glance at the code is to overwrite `ebib--list-keys` but what would you suggest?

Thx

**Comment by kuerzn** [comment]
Ok, I just found out, that you can filter based on key using the `=key=` field. Could you add this to the documentation (info, `ebib--search-in-entry`, ..).

Where are the special fields documentet?

**Comment by joostkremers** [comment]
There are only two such fields, `=key=
