### ISSUE TITLE
Sorting the index

### ISSUE THREAD

**Issue by kuerzn** [joostkremers/ebib#77]
It would be great to be able to sort the index by one or several fields. Is this possible right now? Where would be the best way to start implementing that?

Sorting by date is especially important to me...

**Comment by joostkremers** [comment]
No, it's not possible at the moment. It's certainly possible to add the option to sort the index on the contents of a specific field (e.g., `timestamp` or `date`, etc.) but it'll require some thinking to get it right. (What to do with entries that don't have the relevant field, for example.)

**Comment by kuerzn** [comment]
Do you have other suggestions? I hated all previous Citation Managers (Mendely, Zotero, Endnote), but the one thing they could was simply click on a field and sort...

How do you use ebib? Usually the time order of papers is very important (i.e. what came earlier and builds on top of what other paper...)

> What to do with entries that don't have the relevant field?

Thats easy: Empty values should come last.

**Comment by joostkremers** [comment]
I implemented sorting the index on a specific field. You can now sort by pressing `<` (for ascending sorting) or `>` (for descending sorting) and providing the field to sort on. The contents of the field being sorted on is displayed in the index buffer next to the entry key. Return to the default sorting (i.e., on entry key) with `=`.

I'd appreciate it if you could try it out and see how it works for you. I'm open to suggestions for improvements, so if there's anything you'd like done differently, let me know.

**Comment by kuerzn** [comment]
I installed the MELPA version 20150602, disabled all customizations and when I press `<`

    byte-code: Wrong type argument: symbolp, "=key="

Another question: How can I test your github code? Uninstall the ebib package and load it manually directly from the git folder?

**Comment by scottmartincampbell** [comment]
I've tried the new index sorting and it's great. Fabulously useful. Didn't seem to work on a filtered database, though I didn't test it much. Should it?

**Comment by joostkremers** [comment]
> ```
> byte-code: Wrong type argument: symbolp, "=key="
> ```

That's weird… Is it possible to get a backtrace from that error? (Do `M-x toggle-debug-on-error` and copy & paste the contents of the debug buffer.)

Also, what’s your Emacs version?

> Another question: How can I test your github code? Uninstall the ebib package and load it manually directly from the git folder?

If you installed through MELPA, you automatically get the latest version when you update your packages. (There’ll be some delay between me pushing the latest commits and them being available in MELPA, but IME it’s never more than a few hours.)

Loading Ebib directly from the source folder would be possible, though you’ll either need to load the files in the correct order or add the source folder to your `load-path`.

**Comment by kuerzn** [comment]
The problem seems to be `ebib--field-history`:

```lisp
Debugger entered--Lisp error: (wrong-type-argument symbolp "year")
  read-from-minibuffer("Sort field: " nil (keymap (10 . minibuffer-complete-and-exit) (13 . minibuffer-complete-and-exit) keymap (menu-bar keymap (minibuf "Minibuf" keymap (tab menu-item "Complete" minibuffer-complete :help "Complete as far as possible") (space menu-item "Complete Word" minibuffer-complete-word :help "Complete at most one word") (63 menu-item "List Completions" minibuffer-completion-help :help "Display all possible completions") "Minibuf")) (27 keymap (118 . switch-to-completions)) (prior . switch-to-completions) (63 . minibuffer-completion-help) (32 . minibuffer-complete-word) (9 . minibuffer-complete) keymap (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the minibuffer") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuffer") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence  :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . exit-minibuffer) (13 . exit-minibuffer) (7 . abort-recursive-edit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-history-element) (next . next-history-element) (27 keymap (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) nil ("year") nil nil)
  completing-read-default("Sort field: " ("author" "title" "journal" "year" "volume" "number" "pages" "month" "note" "crossref" "annote" "abstract" "keywords" "file" "timestamp" "url" "doi" "booktitle" "editor" "series" "address" "organization" "publisher" "type" "chapter" "edition" "howpublished" "school" "institution") nil t nil ("year") nil nil)
  completing-read("Sort field: " ("author" "title" "journal" "year" "volume" "number" "pages" "month" "note" "crossref" "annote" "abstract" "keywords" "file" "timestamp" "url" "doi" "booktitle" "editor" "series" "address" "organization" "publisher" "type" "chapter" "edition" "howpublished" "school" "institution") nil t nil ("year"))
  (list (completing-read "Sort field: " (ebib--list-fields-uniquely (ebib--get-dialect)) nil t nil ebib--field-history))
  #<subr call-interactively>(ebib-index-sort-ascending nil nil)
```

Also, I already have the key, year and title in my index (why would anyone only have the key?!), so after searching I have the year twice in my index.

**Comment by joostkremers** [comment]
> The problem seems to be `ebib--field-history`:

Thanks. The `byte-code` function confused me. This should be fixed now.

> Also, I already have the key, year and title in my index (why would anyone only have the key?!),

Well, my keys have the year in them. :)

> so after searching I have the year twice in my index.

Yeah, didn't think about that. Should also be fixed now.

**Comment by joostkremers** [comment]
> I've tried the new index sorting and it's great. Fabulously useful.

Good to hear. :) Thanks to kuerzn for the suggestion.

> Didn't seem to work on a filtered database, though I didn't test it much. Should it?

Well, yes and no. The code wasn’t there to make it work on filtered databases. From a user’s perspective, however, there’s no reason why it shouldn’t.

It should work now, let me know if you run into problems.

**Comment by joostkremers** [comment]
I just realised I should probably use `tabulated-list-mode` for the entry buffer. That should provide a more familiar interface.

**Comment by kuerzn** [comment]
Also for the index, as it already provides sorting ...?

**Comment by joostkremers** [comment]
Sorry, I meant the index buffer.
