### ISSUE TITLE
Sorting and file local variables

### ISSUE THREAD

**Issue by brabalan** [joostkremers/ebib#78]
I have this at the end of my bib file, to make sure the dialect is set correctly when I directly view it:
```
@Comment{
  Local Variables:
  bibtex-dialect: biblatex
  End:
}
```

Unfortunately, each time I add an entry through ebib, this comment block ends up at the very beginning of the file and is no longer taken into account. Is it possible to avoid moving it?

**Comment by joostkremers** [comment]
Actually, Ebib should already do this, but I just noticed that it doesn't work if you indent the lines of the `@comment` block...

So as a work-around, you can remove the indentation:

    @Comment{
    Local Variables:
    bibtex-dialect: biblatex
    End:
    }

Or wait until I fix this. (I won’t have time today, but I’ll post in this thread once I’ve pushed the fix.)

**Comment by brabalan** [comment]
On 2015-05-28 09:14, Joost Kremers <notifications@github.com> writes:

> Actually, Ebib should already do this, but I just noticed that it doesn't work
> if you indent the lines of the @comment block...
>
> So as a work-around, you can remove the indentation:
>
> @Comment{
> Local Variables:
> bibtex-dialect: biblatex
> End:
> }
>
> Or wait until I fix this. (I won’t have time today, but I’ll post in this
> thread once I’ve pushed the fix.)

Ah, thanks, good to know. I removed the indentation for the moment.

Alan

-- 
OpenPGP Key ID : 040D0A3B4ED2E5C7

**Comment by joostkremers** [comment]
I've implemented a fix, but since Ebib doesn't store the local variable block as text (but rather as an alist), the next time you save the file, the indentation is gone.

Is there any particular reason you prefer the indentation? It wouldn't be difficult for Ebib to add it automatically when saving the file.

**Comment by brabalan** [comment]
On 2015-06-01 23:25, Joost Kremers <notifications@github.com> writes:

> I've implemented a fix, but since Ebib doesn't store the local variable block
> as text (but rather as an alist), the next time you save the file, the
> indentation is gone.
>
> Is there any particular reason you prefer the indentation? It wouldn't be
> difficult for Ebib to add it automatically when saving the file.

Not really, it's there because I use aggressive-indent-mode.

Thanks!

Alan

-- 
OpenPGP Key ID : 040D0A3B4ED2E5C7

**Comment by joostkremers** [comment]
I implemented an option to add indentation to the local variable block (user option `ebib-local-variable-indentation`). By default it's set to an empty string but you can set it to two spaces in case you don

**Comment by brabalan** [comment]
I just updated and it's working great. Thanks a lot!
