### ISSUE TITLE
ebib fails to open Bibtex file that was created by Jabref.

### ISSUE THREAD

**Issue by ottopichlhoefer** [joostkremers/ebib#80]
I would like to work on my bibliography both with ebib and Jabref. Jabref has the possibility of tagging/grouping entries. This is stored at the end of the Bibtex file as comments:

```bibtex
@comment{jabref-meta: groupsversion:3;}

@comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 KeywordGroup:test\;0\;keywords\;test\;0\;0\;;
}
```

When i try to open this file in ebib, an error occurs thwt starts with:

    ebib--local-vars-to-list: Wrong number of arguments: #[(string &optional separators omit-nulls) 

My knowledge of Elisp unfortunately does not suffice to fix this myself.

**Comment by joostkremers** [comment]
I cannot reproduce this... I copied the `@comment`s to a test `.bib` file and opened it in Ebib, which went just fine. Upon saving, the comments are put at the beginning of the `.bib` file (which may or may not be a problem for Jabref, I don't know), but I don't get an error.

If possible, could you try with `emacs -Q`? (You'll have to add the packages on which Ebib depends to the `load-path` with the `--directory` option.)
