### ISSUE TITLE
Local variables truncated on saving

### ISSUE THREAD

**Issue by brabalan** [joostkremers/ebib#83]
I recently changed the local variables of my bib file to add git-auto-commit-mode to it. They now look like this:
```
@Comment{
  Local Variables:
  bibtex-dialect: biblatex
  eval: (git-auto-commit-mode 1)
  End:
}
```

Unfortunately when I use ebib and save the file, the local variables get truncated to this:
```
@Comment{
  Local Variables:
  bibtex-dialect: biblatex
  eval: (git-auto-commit-mode
  End:
}
```

**Comment by joostkremers** [comment]
Yes, that was a genuine bug... Should be fixed now, but let me know if you still run into problems.

Thanks for reporting!

**Comment by brabalan** [comment]
It’s working great, thanks!
