### ISSUE TITLE
After marking an entry move focus to the next one

### ISSUE THREAD

**Issue by oddious** [joostkremers/ebib#84]
Could you please make a configurable option to enable moving to the next line in the index buffer after having marked current entry. The current ebib behaviour is a little bit confusing as it differs from what can be called a typical behaviour in "index-buffer" modes, e.g., dired, ibuffer, org-agenda, mu4e, etc. Thanks!

**Comment by joostkremers** [comment]
This is something that's been bugging me for ages... Don't know why I never bothered to fix it.

I've not implemented it as an option, that seems like overkill. (Though if anyone complains, I'll reconsider.)

**Comment by oddious** [comment]
Thank you for quick response! I suggested an option because I thought the previous behaviour was intentional.
