### ISSUE TITLE
Feature request: copy key of entry at point

### ISSUE THREAD

**Issue by brabalan** [joostkremers/ebib#85]
I often need to copy the key of the entry at point (typically to rename a pdf). I found the `ebib--cur-entry-key` function, but the double dash in the name seems to suggest it's a private function. Is there a way to do it?

**Comment by joostkremers** [comment]
Yes, you can use `ebib--cur-entry-key` in a function of your own: it returns the entry key of the current entry as a string.

Alternatively, I just added a function (should be on Melpa in a few hours) `ebib--create-file-name-from-key`, which takes a key and an extension (without dot) and creates a file name from it.

The reason I created a function to do it is that in the process, it can transform the key in a user-specified manner. There's a user option `ebib-name-transform-function` that holds a function of one argument (the key as a string) and returns a string, the actual name to be used. I use it to transform colons in my keys to underscores, but it can be used to make any kind of imaginable change to the key. See the Ebib manual, section "Notes Files" for details:

https://joostkremers.github.io/ebib/ebib-manual.html#notes-files

(The examples given there are specific to notes files, but the principles apply to `ebib--create-file-name-from-key` as well).

You could use this function as, e.g.:

    (ebib--create-file-name (ebib--cur-entry-key) "pdf")

Of course, you can also just use `ebib--cur-entry-key` directly if all you need to do is add `.pdf`.

Both functions are indeed private functions, but they should be safe to use in your own code. I tend to not make incompatible changes even to private functions, if only to save me the hassle of having to change every invocation in my own code...

**Comment by brabalan** [comment]
Thank you for the detailed comment. I added a key-binding doing a `(kill-new (ebib--cur-entry-key))` and it works great.
