### ISSUE TITLE
Idea: Templates, or "recent" fields

### ISSUE THREAD

**Issue by scottmartincampbell** [joostkremers/ebib#87]
I've been using ebib a lot lately in a fairly repetitive way: each entry is almost the same as the last, with just one or two different fields. It would be great if there were a way to create new entries by selecting from a template, which auto-fills the fields based on the template. Alternatively, if there was a way ebib could suggest recently used data when editing a blank field, that would be helpful. To take the idea further, if there were a way for suggestions to work for fields based on existing entries (ie: authors, journal titles, publishers, locations), it would help maintain consistency. 

For context, I'm working on some archival material, and there's very little variation from one entry to the next. Often, I'm only editing one or two field and there's six or seven that remain the same. 

I haven't looked at the code yet to see about implementation, but thought I'd see if others would find this useful and see what Joost might think.

**Comment by joostkremers** [comment]
There is a function `ebib--add-entry-stub` that you may be able to use for your purpose. It should actually be fairly easy to create a command that duplicates the current entry (though you'll have to be careful with the duplicate entry's `=key=` field. Probably best to use `ebib--generate-temp-key` for it.) It should also be possible to create a new entry from a template. You'd just have to decide how to specify the template, e.g., if it's stored on disk somewhere, in a buffer, etc.

If you come up with some code that is general enough to be useful to others, I could add it to Ebib if you send me a pull request or a patch.
