### ISSUE TITLE
Notes path

### ISSUE THREAD

**Issue by gongzhitaao** [joostkremers/ebib#89]
helm-bibtex supports organizing notes in a different directory than the PDF file directory, i.e., `helm-bibtex-notes-path`.  I think I might be convenient if this is also supported in ebib so that helm-bibtex and ebib may both be used to manage the notes.

**Comment by joostkremers** [comment]
Yes, I think that would be a good idea. Perhaps there should also be a separate option for modifying the file name (i.e., `ebib-name-transform-function`).

I'll see about implementing this as soon as I have some time.

**Comment by joostkremers** [comment]
I added two new options, `ebib-notes-directory` and `ebib-note-name-transform-function`. Both default to `nil`, which means the old behaviour applies (i.e., notes are stored in the first directory if `ebib-file-search-dirs` and `ebib-name-transform-function` is applied). But they can be set to their own values to keep the notes files somewhere else and to have them named differently than the pdf files (though I suspect most would find that unpractical).

Let me know if you run into any trouble.

**Comment by gongzhitaao** [comment]
Thanks.  I will try it out!
