### ISSUE TITLE
Jumping to an entry from auctex

### ISSUE THREAD

**Issue by kuerzn** [joostkremers/ebib#92]
Is there a way to jump to an entry corresponding to the \cite{bla} under point?

**Comment by joostkremers** [comment]
Just calling `M-x ebib` (or whatever key sequence you've bound to it, of course) with point on the key should do that, provided the relevant database is loaded. Also, point has to be inside the braces (though it shouldn't be too difficult to change that).

**Comment by kuerzn** [comment]
Does not work here (Version: 20160222.448), jumps to ebib buffer, but not the correct entry

**Comment by joostkremers** [comment]
That's strange. Does the selected entry in Ebib change when you try this or is it just the entry that was selected before you lowered Ebib?

What is the value of `ebib--local-bibtex-filenames` in your `.tex` buffer after calling Ebib from it? (That is, call Ebib from a `.tex` file, lower it again and do `C-h v ebib--local-bibtex-filenames`). Does it show the file name of your `.bib` file and does that match the file name of the database in Ebib?

**Comment by kuerzn** [comment]
> That's strange. Does the selected entry in Ebib change when you try this or is it just the entry that was selected before you lowered Ebib?

No change

> What is the value of ebib--local-bibtex-filenames in your .tex buffer after calling Ebib from it? (That is, call Ebib from a .tex file, lower it again and do C-h v ebib--local-bibtex-filenames). Does it show the file name of your .bib file and does that match the file name of the database in Ebib?

    ebib--local-bibtex-filenames
    ("../manuell.bib" "../MendeleyBibtexSync/library.bib" "../../Literatur/literatur.bib")

whereas `ebib-preload-bib-files` contains absolute paths.

**Comment by joostkremers** [comment]
Ah, I see the problem. I didn't account for file names starting with `..`. I'll push a fix for it in the next few days, when I find some time.

**Comment by joostkremers** [comment]
I just pushed an update that should fix this. It expands file names in `ebib--local-bibtex-filenames` that contain a directory part. That should allow it to match up with the file name of the database.

Let me know if you run into any trouble.

**Comment by pipping** [comment]
Note to self: This works and it's great, as long as I don't use `\addbibresource{\jobname.bib}`.

**Comment by joostkremers** [comment]
Hmm, that trick never occurred to me. Shouldn't be too difficult to support that. I'll let you know when I come up with something.

**Comment by joostkremers** [comment]
Try the latest commit.

**Comment by pipping** [comment]
Thanks, that works! I only had to apply the following additional fix:

```diff
--- a/ebib.el
+++ b/ebib.el
@@ -3695,7 +3695,9 @@ If no .bib files are found, return the symbol `none'."
       (if files
           (mapcar (lambda (file)
                     (if (string= file "\\jobname.bib")
-                        (setq file (file-name-nondirectory (file-name-sans-extension (buffer-file-name)))))
+                        (setq file (file-name-nondirectory
+                                    (concat (file-name-sans-extension (buffer-file-name))
+                                            (car ebib-bibtex-extensions)))))
                     ;; If a file has a directory part, we expand it, so
                     ;; `ebib--get-db-from-filename' can match it up with a
                     ;; database's file path.
```

**Comment by joostkremers** [comment]
> Thanks, that works! I only had to apply the following additional fix:
[...]

Yes, good point. Thanks for pointing that out.

Also, I completely forgot about `ebib-bibtex-extensions`...

I just pushed the fix.
