### ISSUE TITLE
Bad interaction with melpa scripts messes up info directory node (toc)

### ISSUE THREAD

**Issue by aplaice** [joostkremers/ebib#94]
The `dir` file downloaded from [melpa](https://melpa.org/packages/ebib-20160305.1236.tar) (or simply installed using `package-install`) contains two entries corresponding to ebib:
```
* Menu:

Emacs
     * Ebib: (ebib).            A BibTeX database manager.
* Ebib: (ebib).                         A BibTeX database manager
```
which info appears to dislike, resulting in ebib appearing in its own badly formatted category at the top of the menu.

I think that this is caused by the lines corresponding to the ebib node in `dir` and `ebib.info` not being the same (in the git source) and some script in melpa deciding to be clever and duplicate the ebib entry in `dir`. Since it seems that the relevant section of the info page is generated from `manual/header.texi` changing l23 of `manual/header.texi` and l18 of `dir` to both be (say):
```
* Ebib: (ebib).                         A BibTeX database manager.
```
would (I think) fix the problem.

**Comment by aplaice** [comment]
(Also, thank you for an amazing emacs package!)

**Comment by joostkremers** [comment]
Thanks for pointing this out, I never noticed it myself...

I implemented the fix you suggested. Looks like it should be fixed now.

**Comment by aplaice** [comment]
It works, thanks!
