### ISSUE TITLE
`edition' is missing in the Ebib-entry window.

### ISSUE THREAD

**Issue by wwguo** [joostkremers/ebib#95]
I just began to use package.el and replaced an old version Ebib to the Melpa version. I find that the entry field `edition` is missing.  I tried to add a edition field, but was told that it `hidden`.

**Comment by joostkremers** [comment]
Yup. You can read all about hidden fields here:

https://joostkremers.github.io/ebib/ebib-manual.html#hidden-fields

(There's not much to know. Basically, you can make hidden fields temporarily visible with `H`. If you want `edition` to be permanently visible, customise the option `ebib-hidden-fields`.

**Comment by wwguo** [comment]
Thanks!
