### ISSUE TITLE
How to add a new insert-command?

### ISSUE THREAD

**Issue by wwguo** [joostkremers/ebib#96]
I tried to set `ebib-insertion-commands`, but it was ignored. After pressing `p` in the Ebib-index window, I inputted things like `:cite:%A:'%K'`, but only the entry key is inserted. Only the default `\cite` works.

**Comment by joostkremers** [comment]
The variable `ebib-insertion-commands` has been deprecated for several years now. The variable you're looking for is `ebib-citation-commands`.

(Note: in the manual, I refer to customisable options with the name in which they appear in the Customize buffer (without "Ebib"). So when it says in the manual 'The customisation option that allows you to do this is "Citation Commands"', the corresponding variable is called `ebib-citation-commands`. I should probably make this clearer in the manual.)

**Comment by wwguo** [comment]
Thanks a lot!
