### ISSUE TITLE
`ebib-insert-abbreviation` behaves weird.

### ISSUE THREAD

**Issue by wwguo** [joostkremers/ebib#97]
I defined many `@string`s for journal names. When I press `s` in the ebib-entry window, the abbreviation is added, but the cursor jumps back to the ebib-index window and locates at the next entry. If I press `k` to move the cursor upward, the cursor will pass the entry I just edited and jump to the entry before it.

**Comment by joostkremers** [comment]
This is weird... For me `s` works fine. The only thing that comes to mind is that there might be some old code lying around. Could you try removing all traces of any Ebib installation (both the old one and the one from Melpa), close and restart Emacs and then reinstall Ebib from Melpa?

**Comment by wwguo** [comment]
Actually the problem exists since the old very version of Ebib that I had. Recently, I cleared all my Emacs settings and packages and reinstall all packages. When I'm learning how to use package.el, I reinstalled Ebib several times. the The problem is always there.

**Comment by wwguo** [comment]
I just remember to take a look at *Message* and find an error message: 

`Error during redisplay: (eval (concat " «" (ebib--cur-entry-key) "» " (if (file-readable-p (ebib--create-notes-file-name (ebib--cur-entry-key))) ebib-notes-file-symbol ""))) signaled (wrong-type-argument characterp "~/studio/science/biblio/notes") [8 times]`

**Comment by wwguo** [comment]
`(other-window 1)
;; we can't do this earlier, because we would be writing to the index buffer...
(ebib--redisplay-current-field)
(ebib-next-field))`

I changed `(other-window 1)` to `(other-window -1)`. It works fine now.

**Comment by joostkremers** [comment]
Ah, I see... That `other-window` stuff is a bit of trickery to get the completions to show in the right buffer. I should probably use `with-selected-window` for that.

I'll make that change some time this weekend and let you know. You shouldn't have any trouble after that.

**Comment by joostkremers** [comment]
With this fix, your problem should not occur anymore. Let me know if you do run into further issues, though.

**Comment by wwguo** [comment]
Thanks!

**Comment by joostkremers** [comment]
Thank you for reporting the bug!
