### ISSUE TITLE
DOIs can contain all kinds of characters (and thus so can URLs)

### ISSUE THREAD

**Issue by epipping** [joostkremers/ebib#99]
- Parentheses? Check.
- Semicolons? Check.
- Less-than and greater-than signs? Check.

In particular, this is a valid DOI:

```
10.1002/(SICI)1099-1476(199902)22:3<267::AID-MMA40>3.0.CO;2-A
```

I took it from

```
http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1099-1476(199902)22:3%3C267::AID-MMA40%3E3.0.CO;2-A/abstract
```

Understandably, ebib currently fails to handle this particular DOI properly. Rather than to

```
http://dx.doi.org/10.1002/(SICI)1099-1476(199902)22:3<267::AID-MMA40>3.0.CO;2-A
```

it currently takes me to

```
http://dx.doi.org/10.1002/(SICI)1099-1476(199902)22:3
```

because it ignores anything that comes after the less-than sign. By _it_, I mean `ebib--call-browser` which is passed the right URL but then passes it on to `ebib--extract-urls` which chops off anything after (and including) the first `<`.

**Comment by joostkremers** [comment]
I've pushed a commit that should fix this, at least for DOIs. Basically, Ebib now assumes that the contents of the `doi' field can be passed to the browser unchanged, which seems like a fair assumption to make.

The fix doesn't apply to the `url' field, but perhaps it should.

**Comment by joostkremers** [comment]
Closing this issue after almost two years. :smile: The default value for `ebib-url-regexp` excludes `' " < > ;` and whitespace from URLs. This is a user option so it's possible to adjust the regexp to one's personal needs.
